KD: add kd machine ssh subcommand
koding/koding pull request #10019
Opened 2016-12-13 21:17 UTC by ppknap

This PR adds support for SSH remote connections via `kd machine ssh` subcommand.

Closes: #9889
Depends on: #10018, #9797

## How Has This Been Tested?
**NOTE** that `machinegroup.SSH` method is **not** tested. I'm going to implement test client in `machinegrouptest` package which will simulate real behaviour usign loopback devie on localhost.

## Screenshots (if appropriate):

## Types of changes
- [X] New feature (non-breaking change which adds functionality)

2016-12-15 10:19 UTC, cihangir requested changes
could you please split this into PRs?

2016-12-15 18:16 UTC, ppknap commented
@cihangir done. I split this into three parts. This is the first one, #10036 is the second one and #10037 is the last one.

2016-12-15 21:29 UTC, rjeczalik approved these changes

2016-12-16 07:33 UTC, cihangir approved these changes

2016-12-16 07:33 UTC, cihangir commented
Thanks @ppknap

2016-12-16 07:33 UTC, merged