KD: add support for machine ssh subcommand
koding/koding pull request #10037
Opened 2016-12-15 18:13 UTC by ppknap

This PR adds support for SSH remote connections via kd machine ssh subcommand.

Closes: #9889
Depends on: ~#10018, #9797~, #10019, #10036

2016-12-19 17:26 UTC, ppknap commented
@rjeczalik @cihangir ptal

2016-12-19 18:17 UTC, rjeczalik commented on go/src/koding/klientctl/ctlcli/ctlcli.go
> +			fmt.Fprintf(os.Stderr, "fatal: %s\n", err)
`fmt.Fprintf(os.Stderr, "error executing %q command: %s\n", cmdName, err)`

2016-12-19 18:17 UTC, rjeczalik commented on go/src/koding/klientctl/ctlcli/ctlcli.go
> +			fmt.Fprintf(os.Stderr, "fatal: %s\n", err)
ditto

2016-12-19 18:22 UTC, rjeczalik commented on go/src/koding/klientctl/ctlcli/ctlcli.go
> +			fmt.Fprintf(os.Stderr, "fatal: %s\n", err)
Would you also update places where we print explicitly (like credential.go) to not have duplicate entries?

2016-12-20 09:52 UTC, cihangir approved these changes

2016-12-20 09:53 UTC, rjeczalik requested changes
https://github.com/koding/koding/pull/10037#discussion_r93088909

2016-12-20 13:23 UTC, ppknap commented
@rjeczalik done

2016-12-21 13:39 UTC, rjeczalik approved these changes

2016-12-21 13:40 UTC, merged