Apply for Koding Credits forms
koding/koding pull request #10080
Opened 2016-12-20 23:56 UTC by andrewjcasal

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-12-21 00:14 UTC, andrewjcasal commented
![image](https://cloud.githubusercontent.com/assets/1885776/21372924/4a660a3a-c6cf-11e6-885a-5c3dc66312a0.png)
![image](https://cloud.githubusercontent.com/assets/1885776/21372928/5960769c-c6cf-11e6-8572-f34c42de97b3.png)

2016-12-21 04:45 UTC, sinan requested changes
mainly looks good, please rename the css file and we're good.

2016-12-21 04:45 UTC, sinan commented on docs/_includes/css/signup2.css
> +body {
please rename the file.

2016-12-23 12:44 UTC, sinan approved these changes

2016-12-23 12:45 UTC, merged