Add emailer worker to default configuration
koding/koding pull request #10086
Opened 2016-12-21 14:54 UTC by szkl

Signed-off-by: Sonmez Kartal <sonmez@koding.com>

2016-12-21 15:00 UTC, cihangir approved these changes

2016-12-22 17:21 UTC, gokmen requested changes

2016-12-22 17:21 UTC, gokmen commented on workers/emailer/lib/emailer/emailerworker.coffee
> -    message.Properties.Options.username = message.Properties.Username
this line is required for templates ref: https://github.com/koding/koding/commit/ac61b996cd6bb4ff7dc6d517626453af4f679cd2

2016-12-23 13:45 UTC, szkl commented on workers/emailer/lib/emailer/emailerworker.coffee
> -    message.Properties.Options.username = message.Properties.Username
Fixed.

2016-12-23 13:45 UTC, szkl commented
Updated.

2016-12-24 18:55 UTC, gokmen approved these changes

2016-12-24 18:55 UTC, merged