Two guides added VMs communication & softlayer stack guide
koding/koding pull request #10119
Opened 2016-12-26 22:32 UTC by kwagdy

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-12-27 05:27 UTC, sinan commented on docs/docs/vms-communication/index.md
> +title: VMs Communication
Inter-VM Communication

2016-12-27 05:28 UTC, sinan requested changes
looks good please change the title of the commented one.

2016-12-27 17:56 UTC, kwagdy commented
@sinan done :)

2016-12-28 03:13 UTC, sinan approved these changes

2016-12-28 03:13 UTC, merged