Drewsetski component notification
koding/koding pull request #10218
Opened 2017-01-05 08:09 UTC by hakankaradis

Reopen: #9757

## Screenshots (if appropriate):
![](https://monosnap.com/file/IaSB2wT1oLHRjCkXKrnC5EatiwT7ap.png)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2017-01-08 22:47 UTC, usirin requested changes
@drewsetski  The requested changes are mostly related to the way code is written. Once they are fixed, it looks mergeable.

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/helpers.coffee
> +  if _.keys(types).indexOf(notification.type) is -1
Use `Object.keys`

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/helpers.coffee
> +Timer = (callback, delay) ->
Make this a proper `class`.

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/helpers.coffee
> +  start = undefined
Is there a specific reason why `null` is not being used here?

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/NotificationViewContainer.coffee
> +    ]
use `classnames` npm module here. ref: https://www.npmjs.com/package/classnames

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/NotificationViewContainer.coffee
> +  onNotificationRemove: (uid) =>
remove fat arrow.

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/NotificationView.coffee
> +        className = className.filter (word) -> word isnt styles.kd_notification_dismissible
use `classnames` npm module here. ref: https://www.npmjs.com/package/classnames

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/NotificationView.coffee
> +            return
why explicit `return`?

2017-01-08 22:47 UTC, usirin commented on client/component-lab/Notification/NotificationView.coffee
> +      @style = { zIndex: 100 + @props.index }
remove this from here, and define this as `defaultProps.style`

2017-01-08 22:47 UTC, usirin commented on client/app/lib/util/getVendorTransition.coffee
> +  _.keys(transitions).forEach (transitionKey) ->
Use `Object.keys`

2017-01-25 22:12 UTC, hakankaradis commented
@sinan and @usirin I have updated this pr with new commits of [this pr](https://github.com/koding/koding/pull/10420)

I have removed https://github.com/koding/koding/pull/10420/files#diff-a51377e3c5c5b024cb7f53f96603be57R28 this style line, it doesn't necessary and also fixed this line of code https://github.com/koding/koding/pull/10420/files#diff-a51377e3c5c5b024cb7f53f96603be57R118

2017-01-26 00:06 UTC, sinan commented
@usirin can you please finalize this so that we can start using in the app.

2017-01-26 09:05 UTC, usirin commented on client/component-lab/Notification/NotificationViewContainer.coffee
> +  onNotificationRemove: (uid) =>
@hakankaradis this is still not fixed?

2017-01-26 09:10 UTC, usirin approved these changes

2017-01-26 09:11 UTC, usirin commented
Minor fat arrow issue, but not a blocker. Thanks @hakankaradis

2017-01-26 09:11 UTC, merged