go: update algolia client package
koding/koding pull request #10253
Opened 2017-01-09 19:45 UTC by mehmetalisavas

2017-01-09 19:46 UTC, mehmetalisavas commented
ref: https://github.com/koding/koding/issues/10249

2017-01-10 12:02 UTC, mehmetalisavas commented
ping

2017-01-10 13:24 UTC, mehmetalisavas commented
Actually, it would be nice , these changes could be in a different PR because this PR includes both 3rd party package and algolia updates according to updated package

2017-01-11 09:49 UTC, cihangir commented on go/src/socialapi/workers/algoliaconnector/algoliaconnector/account.go
> +		// nbHits := record.NbHits
remove commented out code completely.

2017-01-11 09:50 UTC, cihangir commented on go/src/socialapi/workers/algoliaconnector/algoliaconnector/algoliaconnector.go
> +	case AttributesToIndex:
👍

2017-01-11 09:51 UTC, cihangir commented on go/src/socialapi/workers/algoliaconnector/algoliaconnector/algoliaconnector_test.go
> +// func makeSureSynonyms(handler *Controller, indexName string, f func([][]string, error) bool) error {
remove these

2017-01-11 09:51 UTC, cihangir commented on go/src/socialapi/workers/algoliaconnector/algoliaconnector/synonyms.go
> +// // addSynonym adds given synonym pairs to the given index. do not worry about
ditto

2017-01-11 09:52 UTC, cihangir requested changes
remove commented out code blocks

2017-01-12 01:47 UTC, mehmetalisavas commented
PTAL

2017-01-12 05:50 UTC, cihangir approved these changes

2017-01-12 05:50 UTC, merged