go: update & add 3rd p. packages  for gometalinter
koding/koding pull request #10478
Opened 2017-02-02 16:41 UTC by mehmetalisavas

2017-02-02 16:51 UTC, cihangir requested changes
please send glide.yaml update & lock file

2017-02-03 15:11 UTC, cihangir commented on go/src/glide.yaml
> +- package: gopkg.in/alecthomas/kingpin.v3-unstable
strange, gometalinter imports both https://godoc.org/github.com/alecthomas/gometalinter?imports

2017-02-06 03:43 UTC, mehmetalisavas commented
PTAL, glide works a bit weird :/ but i've added glide.yaml & glide.lock fields..

2017-02-06 03:43 UTC, mehmetalisavas commented
ref : https://github.com/koding/koding/pull/10477

2017-02-06 08:40 UTC, cihangir approved these changes

2017-02-06 08:40 UTC, merged