Gometalinter script
koding/koding pull request #10477
Opened 2017-02-02 14:36 UTC by mehmetalisavas

2017-02-09 11:55 UTC, cihangir requested changes
there are some small changes, socialapi part LGTM, overall looks good

2017-02-09 11:55 UTC, cihangir commented on go/src/koding/klientctl/mount.go
> +		// the progress after competition - to avoid weird/bad UX and errors.
change all competition to completion in this PR :)

2017-02-09 11:55 UTC, cihangir commented on go/src/koding/remoteapi/client/collaboration/post_remote_api_collaboration_add_responses.go
> -Request processed succesfully
https://github.com/koding/koding/blob/master/scripts/api-generator.coffee#L169

if you change here, all will be fixed

2017-02-09 11:55 UTC, cihangir commented on wercker.yml
> +        code: scripts/wercker/run-command scripts/gometalinter.sh
💯

2017-02-09 11:57 UTC, cihangir commented
cc/ @ppknap please see enabled linters

2017-02-09 14:12 UTC, mehmetalisavas commented
You can review & merge this PR. I will update config.json & move the flags into the config file.

2017-02-09 15:56 UTC, mehmetalisavas commented on go/src/koding/klientctl/mount.go
> +		// the progress after competition - to avoid weird/bad UX and errors.
👍

2017-02-09 15:56 UTC, mehmetalisavas commented on go/src/koding/remoteapi/client/collaboration/post_remote_api_collaboration_add_responses.go
> -Request processed succesfully
👍

2017-02-09 15:56 UTC, mehmetalisavas commented
PTAL

2017-02-10 08:45 UTC, cihangir approved these changes

2017-02-10 16:36 UTC, mehmetalisavas commented
@rjeczalik @ppknap  ping

2017-02-11 01:41 UTC, ppknap approved these changes
LGTM :+1:

2017-02-14 14:03 UTC, mehmetalisavas commented
@rjeczalik  ping :)

2017-02-15 22:41 UTC, cihangir commented
@rjeczalik please check when you have time

2017-02-15 22:41 UTC, merged