Enable adding users to group via JGroup model
koding/koding pull request #10507
Opened 2017-02-06 11:10 UTC by usirin

Therefore allow it to be used by `remote.api`

2017-02-06 14:51 UTC, cihangir requested changes
clean up & bongo secure

2017-02-06 14:51 UTC, cihangir commented on workers/social/lib/social/models/group/index.coffee
> +  @joinUser = (options, callback) ->
if you just add secure here, you will get the client, importing server/bongo is not required

2017-02-06 14:51 UTC, cihangir commented on workers/social/lib/social/models/group/index.test.coffee
> +          JGroup.joinUser joinOptions, (err, result) ->
infact this should fail. because we require an "invitation"

2017-02-06 14:51 UTC, cihangir commented on workers/social/lib/social/models/group/index.test.coffee
> +            JGroup.joinUser joinOptions, (err, result) ->
same here

2017-02-06 14:51 UTC, cihangir commented on workers/social/lib/social/models/group/index.coffee
> +  @joinUser = (options, callback) ->
could you also clean up the server handler of jointeam.coffee?

2017-02-06 17:24 UTC, usirin commented on workers/social/lib/social/models/group/index.test.coffee
> +          JGroup.joinUser joinOptions, (err, result) ->
it's working because `allowedDomains` is set to `['*']`

2017-02-06 17:24 UTC, usirin commented on workers/social/lib/social/models/group/index.test.coffee
> +            JGroup.joinUser joinOptions, (err, result) ->
same here :D

2017-02-06 17:25 UTC, usirin commented on workers/social/lib/social/models/group/index.coffee
> +  @joinUser = (options, callback) ->
:+1:

2017-02-06 20:48 UTC, gokmen requested changes
Currently it's open public for such important actions like adding someone to some group. Let's have a session about it first.

2017-02-06 20:48 UTC, gokmen commented on scripts/api-generator.coffee
> +          example: { token: 'some-uuid-string' }
we don't need to hard code a response if it's only used by one method, instead you can define your example response in place like https://github.com/koding/koding/blob/master/workers/social/lib/social/models/computeproviders/stacktemplate.coffee#L325-L351

2017-02-06 20:48 UTC, gokmen commented on workers/social/lib/social/models/group/index.coffee
> +  @joinUser = secure (client, options, callback) ->
this will allow anyone to join anyone to any group.

2017-02-08 14:34 UTC, usirin commented
@cihangir @gokmen i updated the tests to cover all the cases can `JGroup.joinUser` method, which is basically moving the logic from jointeam handler to this method. 

@gokmen do you think these tests answer your concerns as well?

2017-02-08 14:35 UTC, usirin commented on workers/social/lib/social/models/group/index.coffee
> +  @joinUser = secure (client, options, callback) ->
Tests should show that it's working exactly the same as `jointeam` handler, so it's not open to everyone as long as `allowedDomains` property is not set to `['*']`

2017-02-08 20:01 UTC, gokmen commented
@usirin nope, none of the test can answer my concern while this thing stays as is https://github.com/koding/koding/pull/10507/files#diff-23aa32e384f44c80809d4a6cb4c27095R397 this means "anyone" logged in to "any" team can execute this method and can add "anyone (with password)" to "any" team.

2017-02-08 22:27 UTC, gokmen approved these changes

2017-02-08 22:28 UTC, gokmen commented
> @usirin nope, none of the test can answer my concern while this thing stays as is https://github.com/koding/koding/pull/10507/files#diff-23aa32e384f44c80809d4a6cb4c27095R397 this means "anyone" logged in to "any" team can execute this method and can add "anyone (with password)" to "any" team.

ignore my comment, couldn't see the check with invitation code in the deep group.join flow. it looks good to me now 👍

2017-02-09 11:23 UTC, cihangir approved these changes
awesome, thanks for the refactoring and making test better in shape!

2017-02-09 11:23 UTC, merged