Apply formatting to bash files
koding/koding pull request #10525
Opened 2017-02-07 13:09 UTC by cihangir

```go get -u github.com/mvdan/sh/cmd/shfmt
shfmt -l -w ./scripts/```

2017-02-07 13:21 UTC, cihangir commented
looks better with https://github.com/koding/koding/pull/10525/files?w=1

2017-02-07 13:42 UTC, szkl requested changes

2017-02-07 13:42 UTC, szkl commented on scripts/test-instance/run-test
> +EOF
This will cause a failure. Line 10 is already closing the here document. We can block comment lines between 4 and 8 instead of a here document.

2017-02-07 19:30 UTC, gokmen approved these changes

2017-02-08 12:02 UTC, cihangir commented
@szkl PTAL

2017-02-08 17:49 UTC, szkl approved these changes

2017-02-08 17:49 UTC, merged