Gometalinter config
koding/koding pull request #10547
Opened 2017-02-10 16:45 UTC by mehmetalisavas

update of gometalinter.json file;
metalinter flags are move under the config file

2017-02-10 16:46 UTC, mehmetalisavas commented
once before merged, https://github.com/koding/koding/pull/10477 needs to be merged.

2017-02-16 16:58 UTC, szkl requested changes

2017-02-16 16:58 UTC, szkl commented on go/src/.gometalinter.json
> +  ],
Let's keep `Enable` property at the bottom.

2017-02-16 16:58 UTC, szkl commented on go/src/.gometalinter.json
> +  "Concurrency": 16,
This is the default value.

2017-02-16 17:08 UTC, mehmetalisavas commented on go/src/.gometalinter.json
> +  "Concurrency": 16,
yeah ur right, actually i have written as comment for the specification like this because commenting is not allowed by json.

2017-02-17 19:08 UTC, mehmetalisavas commented
@cihangir PTAL

2017-02-17 19:08 UTC, mehmetalisavas commented
cc/ @szkl

2017-02-17 19:19 UTC, cihangir approved these changes

2017-02-17 19:45 UTC, szkl approved these changes

2017-02-17 19:45 UTC, merged