Channel group cleaner
koding/koding pull request #10565
Opened 2017-02-15 03:17 UTC by mehmetalisavas

2017-02-16 10:06 UTC, cihangir commented on go/src/socialapi/models/channel.go
> +				errs = multierror.Append(errs, err)
you are going to append even if error is nil

2017-02-16 10:07 UTC, cihangir commented on go/src/socialapi/models/channel.go
> +				offset++
offset needs to be increased even if there is an error

2017-02-16 10:08 UTC, cihangir commented on go/src/socialapi/models/channel.go
> +		if len(channels) < (limit / 2) {
i think "limit / 2" is unnecessary, if it is smaller than len(channels) we can assume safe to break out of the loop

2017-02-16 16:36 UTC, mehmetalisavas commented on go/src/socialapi/models/channel.go
> +				errs = multierror.Append(errs, err)
actually, we'r appending only the error except `mgo.ErrNotFound` errors. there is early return on above line while checking `if err==nil{continue}`

2017-02-16 16:39 UTC, mehmetalisavas commented on go/src/socialapi/models/channel.go
> +				offset++
i thought it would be nice to try to fetch Group again. is it guarenteed to get the same error ?

2017-02-16 21:49 UTC, cihangir commented on go/src/socialapi/models/channel.go
> +				offset++
most probably yes

2017-02-16 21:49 UTC, cihangir commented on go/src/socialapi/models/channel.go
> +				errs = multierror.Append(errs, err)
🤦‍♂️ 👍

2017-02-17 13:55 UTC, mehmetalisavas commented
@cihangir ping

2017-02-20 10:35 UTC, cihangir commented on go/src/socialapi/scripts/channelcleaner/channelcleaner_test.go
> +// func accountCreatorWithCount(count int) error {
why this commented out code still here?

2017-02-20 10:35 UTC, cihangir requested changes
commented out code.

2017-02-22 14:10 UTC, cihangir commented
please rebase you branch

2017-02-22 17:48 UTC, cihangir approved these changes

2017-02-22 17:48 UTC, merged