Hot Swap between different versions of client [poc]
koding/koding pull request #10585
Opened 2017-02-17 04:28 UTC by gokmen

![](http://g.recordit.co/HfUtKX2m8X.gif)

2017-02-17 09:53 UTC, cihangir commented on workers/social/lib/social/render/scriptblock.coffee
> +    <script src="/a/p/p/#{KONFIG._CLIENTVERSION}/bundle.main.js"></script>
there are other usages as well

```
workers/social/lib/social/render/loggedout/kodinghome.coffee
workers/social/lib/social/render/loggedout/tags/hackathon.coffee
workers/social/lib/social/render/loggedout/tags/landing.coffee
workers/social/lib/social/render/styleblock.coffee
```

but not sure if all are in use

2017-02-17 21:10 UTC, szkl requested changes
S3 can host the client version file if enabled in the configuration eventually.

2017-02-17 21:10 UTC, szkl commented on config/generateRunFile.coffee
> +    elif [ "$1" == "switch" ]; then
switch-client name would be more explicit.

2017-02-17 21:10 UTC, szkl commented on config/generateRunFile.coffee
> +      elif [ -d "./website/a/p/p/$1" ]; then
$KONFIG_PROJECTROOT/a/p/p/$1

2017-02-17 21:10 UTC, szkl commented on servers/lib/server/readclientversion.coffee
> +  KONFIG._CLIENTVERSION = version
How about setting read version to `KONFIG.client.version` property?

2017-02-17 21:10 UTC, szkl commented on config/generateRunFile.coffee
> +      elif [ -d "./website/a/p/p/$1" ]; then
This is not required for koding.com, though. nginx can reverse proxy from S3.

2017-02-18 00:03 UTC, gokmen commented on workers/social/lib/social/render/scriptblock.coffee
> +    <script src="/a/p/p/#{KONFIG._CLIENTVERSION}/bundle.main.js"></script>
```
workers/social/lib/social/render/loggedout/kodinghome.coffee
workers/social/lib/social/render/loggedout/tags/hackathon.coffee
workers/social/lib/social/render/loggedout/tags/landing.coffee
```
these are not using main app styles/app files so we can safely ignore these, but
```
workers/social/lib/social/render/styleblock.coffee
```
this one important that I missed, thanks!

2017-02-18 00:49 UTC, gokmen commented on config/generateRunFile.coffee
> +      elif [ -d "./website/a/p/p/$1" ]; then
yes, I've removed the directory check since we can now use the reverse proxy over S3 for any compiled version.

2017-02-18 00:49 UTC, gokmen commented on config/generateRunFile.coffee
> +    elif [ "$1" == "switch" ]; then
made it `switchclient` like in `buildclient`

2017-02-18 01:08 UTC, szkl approved these changes

2017-02-18 01:08 UTC, szkl commented
> This branch has conflicts that must be resolved

2017-02-18 01:40 UTC, merged

2017-02-20 10:07 UTC, cihangir commented on servers/lib/server/readclientversion.coffee
> +  if KONFIG.environment in [ 'sandbox', 'production' ]
env name approach is problematic where we might create problems for prod while we are on latest env.

scenario:
  * deploy to latest
  * switch version in latest (so it is prod)
  * a new prod machine spins up, gets the new version
  * we reverted the change on latest
  * we didnt run "switchClient" in prod machines.

i would suggest to use "KONFIG_EBENVNAME=koding-latest" property, it is set on compile time.

2017-02-20 10:08 UTC, cihangir commented on servers/lib/server/index.coffee
> +app.get  '/-/version'                            , (req, res) -> res.jsonp { version: KONFIG.version, client_version: KONFIG._CLIENTVERSION }
👍