Replace git-rev with git-rev-sync
koding/koding pull request #10611
Opened 2017-02-20 04:15 UTC by szkl

Signed-off-by: Sonmez Kartal <sonmez@koding.com>

2017-02-20 09:24 UTC, cihangir commented on configure
> +  version = require('git-rev-sync').short()
`version = str.substring 0, 8` is required - there are other places where we apply string expansions

2017-02-20 09:24 UTC, cihangir commented on configure
> +  version = require('git-rev-sync').short()
or we need to fix other places as well :)

2017-02-20 09:25 UTC, cihangir commented on package.json
> +    "git-rev-sync": "1.8.0",
👍

2017-02-20 09:28 UTC, cihangir commented on configure
> +  request "https://p.koding.com/-/ip", (err, res, body) ->
also there is https://www.npmjs.com/package/sync-request :)

2017-02-20 10:30 UTC, cihangir requested changes
substring

2017-02-20 17:16 UTC, szkl commented on configure
> +  version = require('git-rev-sync').short()
I've found no other reference to git-rev module.

2017-02-22 14:12 UTC, cihangir approved these changes

2017-02-22 14:12 UTC, merged