Use JGroupData for countly credentials
koding/koding pull request #10927
Opened 2017-03-31 20:07 UTC by cihangir

2017-04-05 21:59 UTC, cihangir commented
@diclee this PR will prevent gitlab integration from working properly until we run the migrations. Mostly prob while you are testing on latest it will fail. fyi.

2017-04-05 22:00 UTC, cihangir commented on .circleci/config.yml
> +      - image: koding/countly-server:latest
cc// @szkl

2017-04-05 22:00 UTC, cihangir commented on client/analytics/lib/analyticsappview.js
> +    var username =  'admin'
@sinan we need to get the real info with `remote.api.JGroupData.fetchByKey 'countly', callback`

2017-04-05 22:01 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +      payload     : Object
@gokmen i had to rename this field, bongo was overriding it. i tried to refactor bongo but that required a lot of effort and reverted my changes.

2017-04-05 22:02 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +  @fetchDataAt: (slug, path, callback) ->
moved the functionality that we have in group/index to here

2017-04-05 22:02 UTC, cihangir commented on workers/social/lib/social/models/proxy/index.coffee
> -jraphical   = require 'jraphical'
not sure how these survived my clean up

2017-04-05 22:29 UTC, gokmen requested changes
This will break GitHub flow with organization setup and also login via GitHub. We may need to check that out. And on the other hand we also need to define a way to set accessLevel on group data; JGroupData was designed to keep secret data of group which only admins/owners of the group can read/write but with this change it will allow any member (right now anyone but it can be fixed see https://github.com/koding/koding/pull/10927/files#r110040692) to read them. In GitHub case it's dangerous since any member of the team can access the organization token and so on.

2017-04-05 22:29 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +  @fetchByKey = secure (client, path, callback) ->
we need to use `permit` here otherwise anyone can call this over any `JGroup` instances.

2017-04-05 22:29 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +    availableKeys = [ 'countly' ]
we can define these keys in config maybe.

2017-04-05 22:29 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +      return callback new Error 'path is forbidden'
`unless path in availableKeys`

2017-04-05 22:29 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +    slug = client.context.group
better to check `client` existence, if you use `permit` it'll be there probably.

2017-04-05 22:29 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +    whitelist  = ['github.organizationToken', 'test_key__' ]
maybe we can move these too to config.

2017-04-06 08:32 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +  @fetchByKey = secure (client, path, callback) ->
permitted version is in JGroup as you wrote it, nothing changed on that flow [see here](https://github.com/koding/koding/blob/master/workers/social/lib/social/models/group/index.coffee#L580-L585)

"fetchDataAt" is used with permit and only allows admins
"fetchByKey" is used without permit and only allows fetching "predefined keys" by anyone in the team

2017-04-06 08:33 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +    availableKeys = [ 'countly' ]
i didnt move them to config since we dont expect them to change by diff envs. do we?

2017-04-06 08:34 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +      return callback new Error 'path is forbidden'
👍

2017-04-06 08:34 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +    slug = client.context.group
👍

2017-04-06 14:00 UTC, szkl approved these changes

2017-04-06 15:24 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +  @fetchByKey = secure (client, path, callback) ->
currently `fetchByKey` can be called by **anyone** whether they are in team or not. we need to use `permit` here to check group membership.

2017-04-06 16:20 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +    availableKeys = [ 'countly' ]
you're right 👍

2017-04-06 16:21 UTC, cihangir commented on workers/social/lib/social/models/group/groupdata.coffee
> +  @fetchByKey = secure (client, path, callback) ->
Yes that is right, but please see line 64. It will fetch the current group's data, not from the ones you don't belong to.

2017-04-06 18:04 UTC, gokmen commented on workers/social/lib/social/models/group/groupdata.coffee
> +  @fetchByKey = secure (client, path, callback) ->
Ah I see, but better to do it in correct way with `permit` which we can prevent `guest` sessions or we can change the permission type if needed.

2017-04-06 18:56 UTC, rjeczalik commented on go/src/koding/db/models/countly.go
> +	return true
```
return c != nil && c.APIKey != ""
```

2017-04-06 18:59 UTC, rjeczalik commented on go/src/koding/db/mongodb/modelhelper/groupdata.go
> +	err := GetGroupDataPath(slug, path, &gdp)
gdp is already a pointer

```
err := GetGroupDataPath(slug, path, gdp)
```

2017-04-06 19:06 UTC, rjeczalik approved these changes

2017-04-07 08:06 UTC, cihangir commented on go/src/koding/db/models/countly.go
> -	if c == nil {
i find separate version more readable

2017-04-10 19:51 UTC, gokmen approved these changes

2017-04-10 19:54 UTC, gokmen commented
just rebased and force pushed to make sure tests passes, fyi.

2017-04-10 21:22 UTC, merged