[Reopen]: Changed styles for landing page #10981
koding/koding pull request #11017
Opened 2017-04-20 22:49 UTC by hakankaradis

Feature page, services screenshots

![aws](https://monosnap.com/file/crTlxC0DB48HhliCAEQVv3eolpjSfe.png)
![do](https://monosnap.com/file/iqoXeyMJl0dubkGSNmtz9C5w1PUeak.png)
![open stack](https://monosnap.com/file/3KenRSq11iuGO0Cli1D9YboUsJD3et.png)
![vagrant](https://monosnap.com/file/1B0Dw7NtIocogQWnnLlpiat75tq770.png)
![azure](https://monosnap.com/file/NZarb6JjAL4p7R8gzEKWaRmnDsuONg.png)
![gcp](https://monosnap.com/file/3Svkn5ZprECEC7mylGkUgkTCprWpQl.png)
![docker](https://monosnap.com/file/6G8XrojQcpTMXYTkCMQDMUmzyA6kZ7.png)
![soft layer](https://monosnap.com/file/ExswomHHZorzvpC5sadvB2U7xuBG1J.png)
![mesos](https://monosnap.com/file/NZ4MbFSaqag6bhvPMOJyTbJqZtEw8Q.png)

2017-04-20 22:51 UTC, hakankaradis commented
@sinan the pr is LGTM, can you please check the css files?

2017-04-21 00:40 UTC, sinan requested changes
👍 @drewsetski @hakankaradis

2017-04-21 00:40 UTC, sinan commented on docs/blog/index.html
> +          atque corrupti quos dolores et quas molestias excepturi sint.</p>
@ftasdelen ^^

2017-04-21 00:40 UTC, sinan commented on docs/assets/img/landing/company-logos/logo_vagrant.svg
> +</svg>
we need to optimize those svg's, see: https://jakearchibald.github.io/svgomg/

2017-04-21 00:40 UTC, sinan commented on docs/_includes/home/svgs.html
> +            fill-rule="nonzero"></path>
make sure that the svg's look good in home page @hakankaradis

2017-04-21 00:40 UTC, sinan commented on docs/_css/_mixins.scss
> +}
good use of `@mixin`s @drewsetski 👍

2017-04-21 00:40 UTC, sinan commented on docs/_css/code.scss
> +      box-sizing: border-box;
`@include border-box;`

2017-04-21 19:45 UTC, hakankaradis commented on docs/assets/img/landing/company-logos/logo_vagrant.svg
> +</svg>
I will update the those svg's

2017-04-25 22:11 UTC, hakankaradis commented
![](https://monosnap.com/file/Fb2w13lROFKQDBvR221VbElaHs6Z8Y.png)

2017-05-04 08:51 UTC, sinan approved these changes

2017-05-04 08:51 UTC, merged