Reopen: IDE Search Func UI Fix
koding/koding pull request #11133
Opened 2017-05-03 21:28 UTC by hakankaradis

2017-05-03 21:29 UTC, hakankaradis commented
Fixes: #9168

2017-05-04 09:34 UTC, sinan requested changes
@hakankaradis can you address the comments please.

2017-05-04 09:34 UTC, sinan commented on client/app/styl/commons/appfn.styl
> +msk(prop, args)
👍

2017-05-04 09:34 UTC, sinan commented on client/app/styl/commons/appfn.styl
> +s-sprite(folder, name)
👍

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +    exclureDirs     = Object.keys editorSettings.ignoreDirectories
`excludeDirs` typo

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +  escapeRegExp: (str) -> str.replace /([.*+?\^${}()|\[\]\/\\])/g, '\\$1'
keep all the regular expressions in a constant on top of the file above class description.

e.g.

```coffee
REGEXES =
  escapeRegExp: /([.*+?\^${}()|\[\]\/\\])/g
  escapeShell: /([\\"'`$\s\(\)<>])/g
…
```

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +    contextLineRegex        = /^([\s\S]+)\-(\d+)\-([\s\S]*)$/
in the constant above.

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +      keydown      : _.bind @handleKeyDown, this
`@bound ...`

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +      keydown      : _.bind @handleKeyDown, this
`@bound …`

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +_                           = require 'lodash'
not necessary

2017-05-04 09:34 UTC, sinan commented on client/ide/lib/views/filefinder/idefilefinder.coffee
>        keyup        : _.bind @handleKeyUp, this
`@bound` also remove lodash unless used other places.

2017-05-04 21:17 UTC, sinan requested changes

2017-05-04 21:17 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +    uber = JView::destroy.bind this
remove

2017-05-04 21:17 UTC, sinan commented on client/ide/lib/views/contentsearch/idecontentsearchview.coffee
> +  contextLineRegex : /^([\s\S]+)\-(\d+)\-([\s\S]*)$/
pls be consistent either call it `regex` or `regexp`, `regex` is more widely used.

2017-05-04 21:17 UTC, sinan commented on client/ide/lib/views/filefinder/idefilefinder.coffee
> +      placeholder  : 'Type a filename to search...'
use ellipsis `…` instead of three dots `...` tip: `opt + ;`

2017-05-10 04:47 UTC, hakankaradis commented
@sinan pr is updated.

2017-05-10 05:02 UTC, sinan approved these changes
this is from earlier commits I see, you can fix that one later.

2017-05-10 05:02 UTC, sinan commented on client/ace/lib/acefindandreplaceview.coffee
>        keydown      : _.bind @handleKeyDown, this, yes
lodash^

2017-05-15 19:15 UTC, merged