NSE: Docs support
koding/koding pull request #11150
Opened 2017-05-09 01:34 UTC by gokmen

![](http://g.recordit.co/KwaKfxGbLy.gif)

2017-05-09 01:54 UTC, sinan requested changes
👍

2017-05-09 01:54 UTC, sinan commented on client/new-stack-editor/lib/views/index.coffee
>            message  : 'Clonning...'
`Cloning…`

2017-05-09 01:54 UTC, sinan commented on client/new-stack-editor/lib/views/sideview.coffee
> +    { expanded, collapsed = yes } = options
show as is (with the prev state) `unless options`
show expanded `if options.expanded`
show collapsed `unless options.expanded`

2017-05-10 02:41 UTC, gokmen commented
@sinan all addressed and updated.

2017-05-10 05:03 UTC, sinan approved these changes

2017-05-10 05:03 UTC, merged