Fallback to a generic error view when the card is declined
koding/koding pull request #11420
Opened 2017-09-05 14:45 UTC by usirin

fixes the problem of https://twitter.com/cdinu/status/901548830621040641

@sinan I hunted down the response he got in stripe, and recorded this video especially with the same error object which is:

```js
{
    "message": "Your card was declined.",
    "type": "card_error",
    "code": "card_declined",
    "decline_code": "do_not_honor"
}
```

![landing-billing-generic-errors](https://user-images.githubusercontent.com/1783869/30066761-88a882ce-9261-11e7-88e6-f2dff936ea8d.gif)

Also generic error messages are parsed from https://stripe.com/docs/declines/codes and replaced the sensitive error messages with generic ones.

2017-09-05 14:47 UTC, usirin commented
Btw, the reason for errors not showing up before this PR is that stripe changed their response format again, i needed to parse it to make it work again.

https://github.com/koding/koding/pull/11420/commits/3109c160bc5aa2a274921d938f7bef1844f181bb fixes that problem.

2017-09-05 14:52 UTC, szkl approved these changes

2017-09-15 07:20 UTC, sinan requested changes
🙏 sorry forgot to review this one. 👍 looks good thx, two minor things tho:
 - [ ] when failed the action should read: "Use a different card"
 - [ ] and the commented try/catch

2017-09-15 07:20 UTC, sinan commented on client/landing/site.landing/coffee/core/utils.coffee
> +        reject JSON.parse err.responseJSON?.description
trust but verify :) try/catch for json.parse.

2017-09-20 05:48 UTC, sinan commented
ping @usirin

2017-09-20 12:28 UTC, usirin commented
@sinan sorry that i missed the comments, updated now.

2017-09-20 18:21 UTC, usirin commented
@szkl dunno why but builds are failing constantly (go part is not even starting), can you take a look?

2017-09-21 18:18 UTC, sinan approved these changes
👍

2017-09-21 18:18 UTC, merged