Configure with inheriting options flags
koding/koding pull request #11466
Opened 2017-10-19 18:13 UTC by mertaytore

Options flags can now change default values of credentials values for dev environment.

Tests and necessary additions to circleci are also included.

2017-10-20 08:51 UTC, cihangir commented on config/inheritOptionFlags.test.coffee
> +      level3a   : 'test-level3a-value'
Could you make this `level3b` with that way we can ensure that we preserve the existing ones while adding a new property in "level 3" items.

2017-10-20 08:52 UTC, cihangir requested changes
just one small test case

2017-10-24 07:52 UTC, szkl approved these changes

2017-10-25 11:34 UTC, cihangir approved these changes

2017-10-25 11:34 UTC, cihangir commented
👍

2017-10-25 11:34 UTC, merged