Update README to show how to run Koding locally
koding/koding pull request #9064
Opened 2016-09-20 04:28 UTC by hakankaradis

Add description of how to run Koding on locally to Read Me file

2016-09-20 18:17 UTC, szkl commented on README.markdown
> +- [Coffeescript](http://coffeescript.org/)
v1.8.0

2016-09-20 18:18 UTC, szkl commented on README.markdown
> +node -v # make sure your node version is not greater than `0.10.x`
npm version should be checked as well.

2016-09-20 18:18 UTC, szkl commented on README.markdown
> +coffee -v # make sure this doesn't return an error
v1.8.0

2016-09-20 18:20 UTC, szkl commented on README.markdown
> +cd /your/koding/path
Redundant because user is already changed to koding clone path in the previous snippet. You might as well merge snippets.

2016-09-20 18:31 UTC, szkl commented on README.markdown
> +Now you can navigate to [](http://localhost:8090) to see your local Koding
A new line is missing.

2016-09-20 18:31 UTC, szkl commented on README.markdown
> +- [Golang](http://www.golang.org/) v1.7
Go

2016-09-20 18:32 UTC, szkl commented on README.markdown
> +- [Coffeescript](http://coffeescript.org/)
CoffeeScript

2016-09-20 18:32 UTC, szkl commented on README.markdown
> +- [Supervisord](http://supervisord.org/)
Supervisor

2016-09-20 18:34 UTC, szkl requested changes
Just trivial changes.

Make sure lines don't exceed 80 characters length.

2016-09-21 00:03 UTC, hakankaradis commented
@sz updated

2016-09-21 01:00 UTC, szkl commented on README.markdown
> +npm -v # make sure your npm version is greater than 2.15.x
Not greater. It should be in 2.15.x line.

2016-09-21 01:00 UTC, szkl requested changes

2016-09-21 15:23 UTC, hakankaradis commented on README.markdown
> +npm -v # make sure your npm version is greater than 2.15.x
updated

2016-09-21 16:17 UTC, szkl approved these changes

2016-09-21 16:17 UTC, merged