terraformer: enable all providers
koding/koding pull request #9086
Opened 2016-09-21 16:26 UTC by rjeczalik

This PR enables all providers for terraformer.

Context: https://koding.slack.com/files/devrim/F2DFJQY5S/pasted_image_at_2016_09_19_21_12.png

@szkl @cihangir Building all providers increases size of /opt/koding/go/bin from 855M to 1.3G, just FYI as I remember we were running close to the limit of current production block device size.

Related work is to update terraform/terraformer, currently it's blocked by:

https://github.com/koding/koding/issues/9084

Which is going to be done separately to this PR.

2016-09-22 07:52 UTC, cihangir commented
I think the context of that convo was just to enable non-cloud ones since our UI does not support them ATM. Am i correct @devrim @gokmen ?

2016-09-22 07:54 UTC, cihangir requested changes
Thanks for the reminder @rjeczalik  
Lets update the AMI of EB first then merge this cc/ @szkl

2016-09-22 17:55 UTC, gokmen commented
@cihangir yes, any resources which is not known by client-side won't be visible from UI but all those resource will work as is.

2016-09-29 10:57 UTC, rjeczalik commented
@gokmen Do we want all providers enabled or enable only the non-cloud ones? I think we wanted them all, as in:

```
Koding supports everything Terraform supports.
```

http://www.koding.com/docs/what-is-a-stack

2016-09-29 18:02 UTC, gokmen commented
@rjeczalik they will work for sure, but we need to handle them somehow in the ui, like a db resource. we were planning some improvements on that but postponed it for now.

2016-09-29 18:06 UTC, rjeczalik commented
So what about we enable all of them now, and roll out incrementaly ui
support?

On Thursday, 29 September 2016, Gokmen Goksel <notifications@github.com>
wrote:

> @rjeczalik <https://github.com/rjeczalik> they will work for sure, but we
> need to handle them somehow in the ui, like a db resource. we were planning
> some improvements on that but postponed it for now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/koding/koding/pull/9086#issuecomment-250544394>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABG7ITuQLy48FhHdG0Efw9ELTMyxviBNks5qu_1CgaJpZM4KDAtG>
> .
>

2016-09-29 18:07 UTC, devrim commented
+1




- devrim yasar, ceo co-f @koding




On Thu, Sep 29, 2016 at 11:06 AM -0700, "Rafal Jeczalik" <notifications@github.com> wrote:










So what about we enable all of them now, and roll out incrementaly ui

support?



On Thursday, 29 September 2016, Gokmen Goksel <notifications@github.com>

wrote:



> @rjeczalik <https://github.com/rjeczalik> they will work for sure, but we

> need to handle them somehow in the ui, like a db resource. we were planning

> some improvements on that but postponed it for now.

>

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub

> <https://github.com/koding/koding/pull/9086#issuecomment-250544394>, or mute

> the thread

> <https://github.com/notifications/unsubscribe-auth/ABG7ITuQLy48FhHdG0Efw9ELTMyxviBNks5qu_1CgaJpZM4KDAtG>

> .

>





—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-09-29 18:10 UTC, gokmen commented
@rjeczalik said that 7 days ago :) https://github.com/koding/koding/pull/9086#issuecomment-248978512

2016-10-03 18:46 UTC, cihangir approved these changes

2016-10-03 18:48 UTC, merged

2016-10-03 18:48 UTC, cihangir commented
🎉