Google Cloud Platform (GCP) provider support.
koding/koding pull request #9185
Opened 2016-10-03 16:20 UTC by ppknap

This PR adds Google Cloud Platform support for cloud providers.

## Description
Following PR should be rather treated as *alpha* version. It requires functional/integration tests which will be added after #9182 is done.

Blocked by #9184 
Related to #9134 #8165

## Motivation and Context
Possibility to use Google Cloud Platform in Koding.

## How Has This Been Tested?
Some basic unit tests were written. Additionally, templates and API calls were tested manually on Google platform.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-10-03 16:48 UTC, rjeczalik requested changes
```
go/src/vendor/golang.org/x/oauth2/google/default.go:17:2: cannot find package "cloud.google.com/go/compute/metadata" 
```

Dependant PR was merged, please rebase onto master.

2016-10-03 16:56 UTC, ppknap commented
@rjeczalik thanks, will do! However, still waiting for the proper testing lib/env :)

2016-10-04 21:57 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/google.go
> +	Stack:        nil,
missing

2016-10-05 18:35 UTC, ppknap commented
/ptal @cihangir @rjeczalik

2016-10-05 23:26 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/stack.go
> +		if n, ok := instance["count"].(int); ok && n > 1 {
google provider does not support count attribute [0] like AWS one does, so there's no need to generate multiple keys for a single compute_instance resource (the ApplyTemplate will look more like vagrant than aws kloud provider) 

[0] https://www.terraform.io/docs/providers/google/r/compute_instance.html

2016-10-05 23:26 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/stack.go
> +			KiteKey:  fmt.Sprintf("${lookup(var.%s, count.index)}", kiteKeyName),
after fixing https://github.com/koding/koding/pull/9185/files#r82092103 the kitekey can be set directly here

2016-10-05 23:29 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/stack.go
> +		metadata := interfaceToMap(instance["metadata"])
you can simplify this to:

```go
metadata, ok := instance["metadata"].(map[string]interface{})
if !ok {
    metadata = make(map[string]interface{})
}
```

2016-10-05 23:32 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/bootstrap.json.tmpl
> +  "output": {
The bootstrap template is expected to produce output variables - we need to output some variables here (the network id, firewall rule etc.) in order to set Bootstrap struct after bootstrapping.

The frontend calls bootstrap, when bootstrap struct is empty; if bootstrap struct is not updated after successful  bootstrap, then next time template is saved - the bootstrap is going to be called again.

2016-10-05 23:33 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/google.go
> +type Bootstrap struct{}
This should define at least one field that is going to be updated after bootstrap. Empty or nil Bootstrap means no bootstrap, and we do bootstrap for google provider.

2016-10-05 23:35 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/machine.go
> +	ev, withPush := eventer.FromContext(ctx)
We could move this to BaseMachine to reduce further the provider boilerplate. Commenting for posterity.

2016-10-05 23:47 UTC, ppknap commented on go/src/koding/kites/kloud/provider/google/stack.go
> +		if n, ok := instance["count"].(int); ok && n > 1 {
it does support `count` attribute. `count` is a terraform [property](https://www.terraform.io/docs/configuration/resources.html#count) applicable for most terraform resources. 

Here is an example for GCP:

```sh
(archpk) ~/terraform/gce_tests$ grep -C 3 "count" gce_stack.tf.json 
  "resource": {
    "google_compute_instance": {
      "cluster": {
        "count": 2,
        "name": "gce-${var.environment_name}-instance",
        "machine_type": "f1-micro",
        "zone": "us-central1-a",
(archpk) ~/terraform/gce_tests$ terraform plan | grep -A 2 "google_compute_instance"
google_compute_instance.cluster.0: Refreshing state... (ID: gce-development-instance)

The Terraform execution plan has been generated and is shown below.
--
+ google_compute_instance.cluster.0
    can_ip_forward:                                      "false"
    disk.#:                                              "1"
--
+ google_compute_instance.cluster.1
    can_ip_forward:                                      "false"
    disk.#:                                              "1"
```

2016-10-05 23:51 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/stack.go
> +		if n, ok := instance["count"].(int); ok && n > 1 {
TIL thanks for clarification

2016-10-06 20:32 UTC, rjeczalik approved these changes

2016-10-06 20:35 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/google/google.go
> +	Project     string `json:"project" bson:"project" hcl:"project" kloud:",secret"`
This shouldn't be ,secret.

2016-10-07 07:58 UTC, merged

2016-10-07 07:58 UTC, rjeczalik commented
👍