Resource state modal: bug fixes
koding/koding pull request #9201
Opened 2016-10-05 16:01 UTC by alex-ionochkin

## Description
This PR contains error handling fixes in `ResourceStateModal`

## Motivation and Context
- https://github.com/koding/koding/issues/9118
- It fixes VM endless loading animation after team cleanup process. In this case stack status is `Initialized` but VM status is `NotInitialized`. A fix correctly handles such case and shows a proper error message

## Screenshots:
![](http://g.recordit.co/8mNnQSfP6h.gif)

2016-10-05 17:15 UTC, gokmen commented on client/app/lib/providers/resourcestatemodal/controllers/machineflowcontroller.coffee
> +          status     : response.state
this is fixed in kloud it's still `response.State` cc/ @hakankaradis @rjeczalik

2016-10-05 17:16 UTC, gokmen requested changes
this needs to be reverted before merge https://github.com/koding/koding/pull/9201/files#r82023590 rest LGTM

2016-10-05 17:36 UTC, rjeczalik commented on client/app/lib/providers/resourcestatemodal/controllers/machineflowcontroller.coffee
> +          status     : response.state
I'd rather make it `state` in kloud instead.

2016-10-05 17:58 UTC, hakankaradis commented on client/app/lib/providers/resourcestatemodal/controllers/machineflowcontroller.coffee
> +          status     : response.state
Kloud fixed with #9190

2016-10-06 09:13 UTC, alex-ionochkin commented
`MachineFlowController` has been fixed according to the latest kloud fix

2016-10-06 17:55 UTC, gokmen approved these changes

2016-10-06 17:56 UTC, merged