kloud/provider: add Azure support
koding/koding pull request #9241
Opened 2016-10-10 17:09 UTC by rjeczalik

deps: https://github.com/koding/koding/pull/9182

2016-10-17 12:25 UTC, rjeczalik commented
ping

2016-10-17 17:06 UTC, cihangir commented
could you separate the sdk from this PR into another one? github ui does not show the diff

2016-10-17 17:09 UTC, rjeczalik commented
@cihangir Yup sorry, actually I forgot to split it - here it is: https://github.com/koding/koding/pull/9309

2016-10-19 09:16 UTC, rjeczalik commented
split and rebased

On 17 October 2016 at 19:06, Cihangir <notifications@github.com> wrote:

> could you separate the sdk from this PR into another one? github ui does
> not show the diff
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/koding/koding/pull/9241#issuecomment-254269473>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABG7IYLkhhp734Xn6EW3wV8eJzu0vi9Fks5q06segaJpZM4KSyba>
> .
>

2016-10-19 09:19 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/azure.go
> +	Subscriptions []Subscription `xml:"PublishProfile>Subscription"`
xml :/

2016-10-19 09:22 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/azure.go
> +	var found bool
you could simplify with

```
  for _, sub := range pb.Subscriptions {
      if sub.ID == meta.SubscriptionID {
          return nil
      }
  }

  return errors.New("specified subscription ID does not exist")
```

2016-10-19 09:23 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/azure.go
> +	var found bool
yup, will do - when I coded it originally I had two more checks after pb.Subscriptions that's why no early return here

2016-10-19 09:29 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/azure.go
> +var p = &provider.Provider{
you dont need to have this in global scope AFAIS

2016-10-19 09:58 UTC, cihangir requested changes

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/bootstrap_test.go
> +	cases := []*azure.BootstrapConfig{
could you please add test cases for other variables in this struct as well?

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/bootstrap_test.go
> +		if err = json.Unmarshal(tmpl, &v); err != nil {
you can have expected results in a table and check them here

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/machine.go
> +	id, err := m.AzureVMClient.StartRole(m.Meta().HostedServiceID, m.Meta().InstanceID, m.Meta().InstanceID)
could we do something like for all the functions?
```
	ctx, cancel := context.WithTimeout(ctx, 5*time.Minute)
	defer cancel()

	closeChan := make(chan struct{})
	go func() {
		<-ctx.Done()
		close(closeChan)
	}()
	WaitForOperation(closeChan)
```

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/machine.go
> +		ee, ok := err.(management.AzureError)
srsly? sometimes with pointer sometimes not?

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +type BootstrapConfig struct {
linting issues

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +		StorageServiceName: strings.ToLower("kodings" + c.Identifier),
s/kodings/koding-s- ?

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +func (s *Stack) ApplyTemplate(c *stack.Credential) (*stack.Template, error) {
could you please separate this function into smaller ones?

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/stack_test.go
> +      Id="8a523531-2d66-469d-9228-718ad2a58eff"
where these ids come from? safe to be public?

2016-10-19 09:58 UTC, cihangir commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +func (s *Stack) ApplyTemplate(c *stack.Credential) (*stack.Template, error) {
could you write test?

2016-10-19 10:00 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/machine.go
> +		ee, ok := err.(management.AzureError)
Currently they use struct values - without pointers, I'm handling also pointers if they had a second thought and fixed this eventually.

2016-10-19 10:02 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/bootstrap_test.go
> +		if err = json.Unmarshal(tmpl, &v); err != nil {
I don't test for expected values, only for valid JSON - so for every case throwaway `v` variable is used.

2016-10-19 10:03 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +		StorageServiceName: strings.ToLower("kodings" + c.Identifier),
Storage name can't have `-` characters, that's why it differs.

2016-10-19 10:04 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/stack_test.go
> +      Id="8a523531-2d66-469d-9228-718ad2a58eff"
Yes, safe, they are not valid. If they are, then not ours ;-)

2016-10-19 15:39 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/bootstrap_test.go
> +	cases := []*azure.BootstrapConfig{
Done.

2016-10-19 15:39 UTC, rjeczalik commented
@cihangir All addressed, ptal.

2016-10-19 16:47 UTC, ppknap commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +	p, err := Asset(s)
You can use `MustAsset` generated by go-bindata.

2016-10-20 07:59 UTC, cihangir approved these changes
we can merge after deployment

2016-10-20 10:55 UTC, ppknap approved these changes

2016-10-20 12:19 UTC, rjeczalik commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +	vm["endpoint"] = provider.ToSlice(endpoints)
/cc @ppknap 

```
--- PASS: TestAzure_ApplyTemplate (0.01s)
    --- PASS: TestAzure_ApplyTemplate/basic_stack (0.00s)
    --- PASS: TestAzure_ApplyTemplate/custom_stack (0.00s)
```

2016-10-20 13:23 UTC, ppknap commented on go/src/koding/kites/kloud/provider/azure/stack.go
> +	vm["endpoint"] = provider.ToSlice(endpoints)
Should be good for now. However, this method does not work when shadowed element is inside slice.

2016-10-25 18:35 UTC, rjeczalik commented
What about we merge azure before deploy? The feature would be a ~nop without client support.

2016-10-25 22:24 UTC, gokmen commented
@cihangir we can merge this since it seems it won't affect deploy afais.

2016-10-26 06:24 UTC, merged