Add Share With Team and Make Private Menu Items to Stacks
koding/koding pull request #9338
Opened 2016-10-19 06:28 UTC by hakankaradis

Aim of this pr is giving ability to users to share (`Share With Team`) and unshare(`Make Private`) their private stacks with team.

## Description
Draft's sidebar getters updated to show shared stack on sidebar, instead of going stacks page and add to sidebar, now we are going to show all drafts on sidebar by default.

Draft's stack's menu options updated. Shared stack templates menu options came with `Edit` option but now it is `View Stack`

Show `Share With Team` and `Make Private` menu options for stacks.

Remove Validator.own stack template permission to generate stack from shared stack template.

## Bugs

- [ ] Updates came by refresh when shared stack template has update
- [ ] If user delete shared stack template, others will have no longer that stack template.

## Motivation and Context
#9225 

## How Has This Been Tested?

## Screenshots (if appropriate):
http://recordit.co/WpUjt58R9g

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2016-10-27 10:15 UTC, gokmen commented
@hakankaradis ping for bugs mentioned in PR description.

2016-10-27 18:57 UTC, hakankaradis commented
@gokmen I will update you soon, didn't have time to work on it.

2016-10-31 22:56 UTC, hakankaradis commented
- Update SendNotification func signature and add sharedStackTemplates attribute.
- ComputeUtils: fetchGroupStackTemplate update func signature
- ComputeProvider: createGroupStack update func signature
- groupController: update setDefaultTemplate (accept type) to use it for share with team func.

Current group will have all shared stackTemplates ( in stackTemplates and sharedStackTemplates)

- sharedStackTemplates is an array and hold only default stack template id.
- stackTemplates is an array and hold all shared stack template ids.

Currently having problem when user unshare his team stack.
I will update soon. @gokmen

2016-11-01 23:29 UTC, hakankaradis commented
@gokmen here is final screencast, I will push my commits soon. http://recordit.co/EcWgWfFBf6

2016-11-02 11:35 UTC, gokmen commented
@hakankaradis can u fix tests and re-assign me back, thanks.

2016-11-02 22:45 UTC, hakankaradis commented
@gokmen 
I added another control flow for destroying team or shared stack.
Here are the screenshots for admins and members
![](https://monosnap.com/file/tlGP2WUE80yT56JCXYQv96faYdykwS.png)
![](https://monosnap.com/file/SP7jRaACno7HSgLzMvtfZq9uHXRlL6.png)

2016-11-03 16:24 UTC, gokmen requested changes
There will be more comments on this one but can u update the ones commented first, thanks!

2016-11-03 16:24 UTC, gokmen commented on client/app/lib/components/sidebarstacksection/index.coffee
> +          computeController.makeStackPrivate template  unless err
let's move these functions from computeController to JStackTemplate's remote extension and here we can say `template.makePrivate()` and `template.shareStackWithTeam()`

2016-11-03 16:24 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +  makeStackPrivate: (stackTemplate) ->
this shouldn't have a UI code here, just the functionality should be here. If you need to provide some UI helper you can put them into `ComputController.UI`

2016-11-03 16:24 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/computeutils.coffee
> +    _id = if _id then _id else group.sharedStackTemplates?[0] or group.stackTemplates[0]
`_id ?= ...`

2016-11-03 16:24 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/computeutils.coffee
> +    JStackTemplate.one { _id: _id }, (err, template) ->
`{ _id }`

2016-11-04 21:15 UTC, hakankaradis commented
@gokmen  http://recordit.co/8vnFejfVIp

2016-11-07 11:57 UTC, gokmen requested changes
we may need a session for this, it shouldn't be handled in this way. I added some more comments but if you need further information please ping me before taking action.

2016-11-07 11:57 UTC, gokmen commented on client/app/lib/components/sidebar/index.coffee
> +            return @showErrorMessage 'Your stack template successfully cloned'
it looks weird that we're showing a success message over `showErrorMessage` method.

2016-11-07 11:57 UTC, gokmen commented on client/app/lib/components/sidebar/index.coffee
> +  showErrorMessage: (title) -> new kd.NotificationView { title }
better to rename this as `showMessage`

2016-11-07 11:57 UTC, gokmen commented on client/app/lib/components/sidebarstacksection/index.coffee
> +  showErrorMessage: (title) -> new kd.NotificationView { title }
same issue here.

2016-11-07 11:57 UTC, gokmen commented on client/app/lib/components/sidebarstacksection/index.coffee
> +isStackMine = (stackOriginId, myId) -> stackOriginId is myId
no one is using this it seems.

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +        group.modify client, { stackTemplates, sharedStackTemplates }, (err) =>
why do we need that? and why we are keeping this list on `JGroup` instance?
we can get list of templates shared with group by simply `JStackTemplate.some {accessLevel: 'group'}`

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +        group.modify client, { stackTemplates, sharedStackTemplates }, (err) =>
and we shouldn't modify such data from this place at all.

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +        group.modify client, { stackTemplates }, (err) =>
same here, `JGroup` instance data shouldn't be modified by another model such as `JStackTemplate`

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +          return callback err, this
we don't need this method at all, you can simply use `JStackTemplate::setAccess 'group'` from client side. same goes for `makePrivate` method as well.

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +  makeTeamDefault: permit
this is not a feature of `JStackTemplate` it's a feature of `JGroup` and it already has a functionality for this https://github.com/koding/koding/blob/master/workers/social/lib/social/models/group/index.coffee#L1108-L1136

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +
we don't need this change as well.

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/group/index.coffee
> +      sharedStackTemplates: [ ObjectId ]
let's revert this also.

2016-11-07 11:57 UTC, gokmen commented on workers/social/lib/social/models/computeproviders/stacktemplate.coffee
> +          (signature Function)
let's revert this, details are in comments.

2016-11-08 16:02 UTC, gokmen commented
@hakankaradis closing this one, when you're ready we can go over with the new one.

2016-11-08 16:02 UTC, closed without merging