Marketing Pages - Modal
koding/koding pull request #9355
Opened 2016-10-20 20:17 UTC by andrewjcasal

## Description

Modal refactored out into .js and .scss
Additional functionality for playing and pausing YouTube videos.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-10-20 20:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/koding/koding?pullRequest=9355) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/koding/koding?pullRequest=9355) before we can accept your contribution.<br/>

2016-10-24 18:56 UTC, andrewjcasal commented
Hey @usirin can you review this? 😀

2016-10-26 18:02 UTC, sinan requested changes
thx @andrewjcasal, just minor changes needed 👍

2016-10-26 18:02 UTC, sinan commented on docs/_includes/js/modal.js
> +	}
what up with the indentation above?

2016-10-26 18:02 UTC, sinan commented on docs/_includes/js/modal.js
> +	}
this is not a util, therefore `modal.js` name is misleading. you can either call it `store-modal.js` or make it generic and keep the name same.

2016-10-26 18:05 UTC, andrewjcasal commented on docs/_includes/js/modal.js
> +	}
The modal's being used on the Trials page, and will be used on the docs training video page too. Where would be the best place to put this as a util? And what should it be called then?

2016-10-26 18:28 UTC, sinan approved these changes
👍

2016-11-01 19:20 UTC, usirin commented
@sinan left this PR to you, as you know better this area.

2016-11-01 20:46 UTC, sinan commented
@andrewjcasal taking this in but please take a note to fix the modal util to be more generic and allowing for multiple modals, and removing video controls from the modal logic.

2016-11-01 20:47 UTC, merged