Added docs for GCE, DO and Choosing a Provider
koding/koding pull request #9366
Opened 2016-10-21 19:00 UTC by arkigos

## Description

We are adding GCE and DO to our supported providers. These are the Getting Started docs for those providers. Also, a doc comparing all of our providers. NOTE this does not update the navbar links and so these docs will not be linked to until we make that change (presumably after our providers go live).
## Motivation and Context

We needed docs for our new providers! (and a meta doc to compare them)
## How Has This Been Tested?

N/A (could use a few proofreads for typos?)
## Screenshots (if appropriate):
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-10-26 18:14 UTC, sinan commented
thx @arkigos, @sibblegp can you please review the language and content.

2016-10-28 18:30 UTC, sibblegp requested changes
Typos and other changes.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/choose-provider/index.md
> +Vagrant allows you to use your own machine to host your Koding VMs. You will install it along-side VirtualBox, so Vagrant can interface you with all of its features.
"You will install it" -> "It gets installed"

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/choose-provider/index.md
> +DigitalOcean is a very popular option among developers an teams who don't need all of the features of AWS or GCE and also don't need all of the headache. Its feature-set is much smaller than the othe
"an" -> "and".  Remove the line about headache.  "smaller" -> "simpler".  Remove the word strong in "strong active community".

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/choose-provider/index.md
> +> Using DigitalOcean as a provider will require you to [Sign Up](https://cloud.digitalocean.com/registrations/new) for the service. Currently, this requires a credit card and for you to pre-load your
Clarify what a droplet is.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/choose-provider/index.md
> +A Floating IP is a static public IP address that can dynamically map to any VM. This can be used to mask failures by re-routing domains to different instances without needing to change the DNS record
If we can configure floating IPs in Koding, then let's not mention selecting a droplet and clicking a button.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/choose-provider/index.md
> +Google Compute Engine is packed with many features which rival those of AWS. GCE offers competitive pricing, an astonishing uptime, and is fast!
"competitive pricing, astonishing uptime, and speed!"

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/choose-provider/index.md
> +* **Access Control**
Not Koding related.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-digitalocean/index.md
> +Your DigitalOcean Personal Access Token will provide the credentials you need to instantiate your Stacks using DigitalOcean.
"using DigitalOcean on Koding."

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-digitalocean/index.md
> +4. Use the Wizard to create and  populate your Stack with some defaults, make sure you select Digital Ocean as provider
Make selecting Digital Ocean a specific step and then say they can optionally skip the remaining steps or continue to install some default software.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-digitalocean/index.md
> +4. Copy the Personal Access token that you generated [earlier](#create-pat)
"Copy"  ->  "Paste in"

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-digitalocean/index.md
> +Once you've created your Stack and set our credentials:
"set your credentials"

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +Getting started with GCE requires a few
Sentence fragment.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +> Take note not only of the Project Name but the Project ID. You will need this ID when creating credentials for your Koding Stack.
I would emphasize that they should write down or copy the project ID somewhere.  Taking note of it doesn't mean they'll remember it.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +2. Go to your [Dashboard](https://relepic.koding.com/Home) OR click [Stacks](https://relepic.koding.com/Home/Stacks) from your sidebar.
These links are to a specific team.  You can't link to a person's dashboard directly from the docs.  Make sure this is also the case with other dashboard links.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +3. Either way, you'll default to the Stacks screen, so from that screen click [New Stack.](https://relepic.koding.com/Stack-Editor/New)
Same problem of linking to a specific team.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +4. Use the Wizard to create and  populate your Stack with some defaults, make sure you select Google Compute Engine as provider.
Make selecting GCE as a specific step.

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +To add your DigitalOcean credentials:
GCE credentials

2016-10-28 18:30 UTC, sibblegp commented on docs/docs/getting-started-google-compute-enging/index.md
> +6. Set the region of your project.
"Make sure this is the same region you set when creating your project"

2016-11-01 20:24 UTC, gokmen commented
@arkigos can u take a look to issues commented by @sibblegp

2016-11-22 00:16 UTC, gokmen commented
ping.

2016-11-22 01:33 UTC, merged

2016-11-22 01:34 UTC, sinan commented
since these aren't referenced anywhere I merged them, @kwagdy is going to fix and push again.