Koding Issue #9329 - ReadMe Preview and Credential Show Preview Modal…
koding/koding pull request #9388
Opened 2016-10-25 03:04 UTC by jack89129

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

…'s styling needs to be fixed

2016-10-25 17:48 UTC, jack89129 commented
![screenshot from 2016-10-25 10 48 11](https://cloud.githubusercontent.com/assets/19863896/19697531/92e78190-9aa0-11e6-9485-050ad8e57024.png)

2016-10-25 19:47 UTC, sinan requested changes
thx for the PR @jack89129, there are some minor code and styling problems, also styling needs to be applied precisely as per the provided design.

2016-10-25 19:47 UTC, sinan commented on client/app/lib/views/credentiallist/accountcredentiallist.coffee
> +    content = "<p><pre><code>#{cred}</code></pre></p>"
```coffee
content = "<pre><code>#{cred}</code></pre>"
...
scrollView.wrapper.addSubView markdown_content = new kd.CustomHTMLView
  tagName:  'p'
  cssClass : 'markdown-content'
  partial : content
```

2016-10-25 19:47 UTC, sinan commented on client/app/lib/components/contentModal/styl/contentModal.styl
> +      padding                   10px 30px
please take a another look to provided pdf, the spacings are not the same around the code block.

2016-10-25 19:47 UTC, sinan commented on client/app/lib/components/contentModal/styl/contentModal.styl
> +        display                 inline-block
you can get rid of this line, bc `inline-block` seems unnecessary here. `pre` elements default to `block` and that is fine.

2016-10-25 19:47 UTC, sinan commented on client/app/lib/components/contentModal/styl/contentModal.styl
> +          overflow              auto
`overflow` can not be set to `auto` here since you handle scroll in the parent.

2016-10-25 19:47 UTC, sinan commented on client/app/lib/components/contentModal/styl/contentModal.styl
> +          display               inline-block
you probably need no styling for the `code` tag at all. But assuming you do again `display` defaults to `inline` and that should be fine.

2016-10-25 19:47 UTC, sinan commented on client/app/lib/views/credentiallist/accountcredentiallist.coffee
> +    scrollView.wrapper.addSubView markdown_content = new kd.CustomHTMLView
the variable `markdown_content` doesn't seem to be used in this context, pls get rid of it.

2016-10-26 16:51 UTC, jack89129 commented
I have fixed code and styling problems as Sinan's requirements.

![screenshot from 2016-10-26 09 50 07](https://cloud.githubusercontent.com/assets/19863896/19735743/ad9c6d0e-9b61-11e6-9a5b-7dc9f8d2d2ad.png)
![screenshot from 2016-10-26 09 50 25](https://cloud.githubusercontent.com/assets/19863896/19735749/b21baa84-9b61-11e6-8ff2-a03a3d959aa5.png)

2016-10-26 18:05 UTC, sinan commented on client/app/lib/views/credentiallist/accountcredentiallist.coffee
> +    content = "<p><pre><code>#{cred}</code></pre></p>"
by putting the `tagName: 'p'` you can get rid of the `p` wrapper in `content`, pls see the code above.

2016-10-26 18:06 UTC, sinan commented
thx @jack89129, please see https://github.com/koding/koding/pull/9388#discussion_r85184209

2016-10-26 18:38 UTC, jack89129 commented
I Removed p tag as your requirements

2016-10-26 18:45 UTC, jack89129 commented
I reverted removing the tagname option from the code and removed p tag from content

2016-10-26 20:39 UTC, sinan approved these changes

2016-10-26 20:42 UTC, sinan commented
@jack89129 added do-not-merge label, this is not about your changes but a notice to our admins.

2016-11-01 20:25 UTC, gokmen commented
@jack89129 can u rebase and fix conflicts? thanks!

2016-11-01 21:09 UTC, jack89129 commented
I just rebased and resolved conflicts.

2016-11-01 21:10 UTC, merged