Mock Machine IDE (MemoryFsKite, MemoryFsKlient)
koding/koding pull request #9396
Opened 2016-10-26 08:45 UTC by usirin

This PR introduces a new concept to create an IDE with a mock klient/kite instances. It uses the `memory-fs` npm module to create a fs like object in memory, and provides the same api as node.js `fs` module.

This is really a bare bones implementation to see if it's feasible for tests (especially for rainforest) to use, but we can use this as a base fs kite implementation, and build up on it.

/cc @devrim @diclee

2016-11-01 21:15 UTC, usirin commented
@gokmen ready to go.

Here is what it does:

- Hit the `/IDE/test-machine` or `/IDE/test-machine/test-workspace`
- Hit `RUN` button on modal.
- It runs the tests in `tests` array in `/client/ide/lib/test/index.coffee` [here](https://github.com/koding/koding/blob/mock-kite-klient/client/ide/lib/test/browser/index.coffee#L9-L11)
- An example test is located under `/client/ide/lib/test/browser.coffee`

## Screencast

![mock-klient](https://cloud.githubusercontent.com/assets/1783869/19907791/9367bb9c-a03d-11e6-84f6-3f93912643cd.gif)

2016-11-02 17:15 UTC, gokmen requested changes
Looks great in general just some small changes needed, awesome work 💯

2016-11-02 17:15 UTC, gokmen commented on client/app/lib/providers/machine.coffee
> +    return klient  if klient
let's change this one to;

```coffee
testklient = runMiddlewares.sync this, 'getBaseKite', createIfNotExists
return testklient  if testklient
```

2016-11-02 17:15 UTC, gokmen commented on client/app/lib/providers/middlewares/testmachine.coffee
> +module.exports = TestMachineMiddleware =
👍

2016-11-02 17:15 UTC, gokmen commented on client/app/lib/providers/middlewares/testmachine.coffee
> +module.exports = TestMachineMiddleware =
a brief comment would be nice

2016-11-02 17:15 UTC, gokmen commented on client/ide/lib/index.coffee
> -      if not isTeamReactSide() and not machineItem.isMine() and not machineItem.isApproved()
👊

2016-11-02 17:15 UTC, gokmen commented on client/ide/lib/test/browser/example.coffee
> +  fileItemSelector = 'span[title*=bash_rc]'
😕

2016-11-02 17:15 UTC, gokmen commented on client/ide/lib/test/browser/index.coffee
> +# of colocating data with view components.
👍

2016-11-02 17:15 UTC, gokmen commented on client/app/lib/kite/kites/memoryfsklient.coffee
> +module.exports = class MemoryFsKlient extends KodingKite
👍

2016-11-02 17:34 UTC, usirin commented on client/app/lib/kite/kodingkite.coffee
> +    @commandBuffer = new KiteCommandBuffer { kite: this }
👍 You're right.

2016-11-07 11:41 UTC, gokmen requested changes
just small changes, rest LGTM 💯

2016-11-07 11:41 UTC, gokmen commented on client/app/lib/kite/kodingkite.coffee
> +              .then (res) =>
no need for fat arrow here.

2016-11-07 11:41 UTC, gokmen commented on client/app/lib/kite/kodingkite.coffee
> +              .then (res) =>
better to revert any change on this file actually.

2016-11-07 11:41 UTC, gokmen commented on client/app/lib/userenvironmentdataprovider.coffee
> +    if filtered.length then filtered[0] else null
`@getAllMachines().filter(predicate)[0]` ?

2016-11-07 20:44 UTC, usirin commented on client/app/lib/userenvironmentdataprovider.coffee
> +    if filtered.length then filtered[0] else null
👍

2016-11-07 21:32 UTC, devrim commented
awesome job @usirin - @hakankaradis can you create a new issue that outlines the keyb shortcut tests (and maybe others, consult to @diclee ad @szkl) and get it done by an external developer?

2016-11-07 23:13 UTC, gokmen approved these changes

2016-11-07 23:13 UTC, merged