Renaming filename from IDE #9158
koding/koding pull request #9398
Opened 2016-10-26 09:41 UTC by juanramos126

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-10-26 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/koding/koding?pullRequest=9398) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/koding/koding?pullRequest=9398) before we can accept your contribution.<br/>

2016-10-26 10:17 UTC, hakankaradis commented
#9158

2016-10-26 18:11 UTC, sinan requested changes
thx @juanramos126, minor changes needed to get rid of a redundant view.

2016-10-26 18:11 UTC, sinan commented on client/ide/lib/styl/ide.styl
> +        .tab-icon
you can do:

```stylus
&:before
  content ''
  position          absolute
  ...
```

2016-10-26 18:11 UTC, sinan commented on client/ide/lib/styl/ide.styl
> +        &.terminal
and here:

```stylus
&.terminal:after
```

2016-10-26 18:11 UTC, sinan commented on client/ide/lib/views/tabview/idetabhandleview.coffee
> +
and get rid of this extra view.

2016-10-26 19:36 UTC, juanramos126 commented on client/ide/lib/styl/ide.styl
> +        .tab-icon
I tried to remove it and added your style, but it's not work.

2016-10-26 19:39 UTC, juanramos126 commented on client/ide/lib/styl/ide.styl
> +        .tab-icon
If you have slack account, can we make communication there?

2016-10-26 20:36 UTC, sinan commented on client/ide/lib/styl/ide.styl
> +        &:before
👍

2016-10-26 20:42 UTC, sinan commented
@juanramos126 added do-not-merge label, this is not about your changes but a notice to our admins.

2016-10-26 20:43 UTC, juanramos126 commented on client/ide/lib/views/tabview/idetabhandleview.coffee
> +        @titleInput.selectRange(0, title.lastIndexOf('.'))
I updated it.

2016-10-26 20:45 UTC, sinan approved these changes

2016-10-27 08:14 UTC, gokmen commented
@juanramos126 can u fill up PR details correctly as it's requested for the next time? thanks!

2016-11-01 20:19 UTC, merged