Manage team doc
koding/koding pull request #9413
Opened 2016-10-27 19:16 UTC by arkigos

New documentation for team management.

## Description
Adds a single new doc (within a new directory) that outlines all team-related management actions in the UI. 

## Motivation and Context
We were missing documentation for these actions. 

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-10-28 19:50 UTC, sibblegp requested changes
Typos and other changes.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +3. Go through adding your Contact Info, Payment Info, verifying your identity, choosing a support plan.
"and picking a support plan."

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +4. Confirm your information and you should be good to go!
Mention the free tier.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +## Subscribe to EC2 <a name="subscribe"></a>
As I said, I'm not sure this is true anymore but I may be wrong.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +> If you previously signed in to the console with IAM user credentials, your browser might open your IAM user sign-in page. You can't use the user sign-in page to sign in with your root credentials.
The final sentence is a step on its own and should be separate from this paragraph.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +2. Go to your [Dashboard](https://relepic.koding.com/Home) OR click [Stacks](https://relepic.koding.com/Home/Stacks) from your sidebar.
Links go to a specific team.  Also true below.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +> You won't need to worry about the aws_*_key variables. These will be automatically populated when you set up credentials in the next step.
aws_* not aws_*_

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +## Set your Credentials <a name="set-creds"></a>
I think there might be an error in the markdown here as this isn't properly highlighted.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +4. Paste in the ID and Key that you obtained [earlier](#create-key)
Be more specific about Access Key and Secret Key, etc. and which step they obtained them from.  Reference the .csv file they downloaded.

2016-10-28 19:50 UTC, sibblegp commented on docs/docs/getting-started-aws/index.md
> +Once you've created your Stack and set our credentials:
set your credentials

2016-11-22 00:17 UTC, gokmen commented
ping.

2016-11-24 22:20 UTC, closed without merging