Sitemap, Index page img alt text and title change, link to buttons
koding/koding pull request #9478
Opened 2016-11-04 23:10 UTC by andrewjcasal

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-11-05 07:49 UTC, sinan requested changes

2016-11-05 07:49 UTC, sinan commented on docs/index_new.html
>        <p>Install Koding on premisis for both personal use and enterprise solutions</p>
premises*

2016-11-05 07:49 UTC, sinan commented on docs/index_new.html
>      <div class="u-headline">Closing copy blah blah blah</div>
proper copy pls

2016-11-05 07:49 UTC, sinan commented on docs/robots.txt
> +Sitemap: http://www.koding.com/sitemap.xml
👍

2016-11-07 19:18 UTC, andrewjcasal commented on docs/index_new.html
>      <div class="u-headline">Closing copy blah blah blah</div>
There was no proper copy given to me for this. That being said, I will flag down Devrim for copy.

2016-12-06 00:48 UTC, sinan commented
@andrewjcasal please send the sitemap.xml with another PR. closing this since we don't need the other changes anymore.

2016-12-06 00:48 UTC, closed without merging