Stacktemplateshare
koding/koding pull request #9514
Opened 2016-11-09 00:23 UTC by hakankaradis

WIP
@gokmen we need to define the flow for `Make Private` feature for generated stack ones.

Here is the scenerio; User1 share stack template, User2 generates a stack by using shared stack template. User 1 make the stack template private, What will happen to User2's stack?

2016-11-11 23:29 UTC, hakankaradis commented on client/stack-editor/lib/index.coffee
> +            if stackTemplate.template.sum isnt originalTemplate.template.sum
It looks weird but when stack-editor view is open for member, and when admin update the original stack template, I need to add the update event here.

2016-11-11 23:31 UTC, hakankaradis commented on client/stack-editor/lib/index.coffee
> +    # stackTemplate.on? 'update', =>
I commented out those lines because of #9527.
I think we need to get rid of those lines? @gokmen

2016-11-11 23:31 UTC, hakankaradis commented on client/stack-editor/lib/styl/stackeditor.styl
> +    div.tooltip span.tooltiptext
I'll update tooltip style soon.

2016-11-14 09:01 UTC, gokmen requested changes
LGTM in general just small changes and we can have another session before taking this in.

2016-11-14 09:01 UTC, gokmen commented on client/stack-editor/lib/index.coffee
> +    # stackTemplate.on? 'update', =>
nope we need to fix that issue, not sure how.

2016-11-14 09:01 UTC, gokmen commented on workers/social/lib/social/traits/notifiable.coffee
> +  updateTemplateAndNotify: (options, change, callback) ->
traits shouldn't include something specific to a model, they are generic. we can move this into `JStackTemplate` model instead.

2016-11-14 19:35 UTC, gokmen commented on client/stack-editor/lib/index.coffee
> +    # stackTemplate.on? 'update', =>
@hakankaradis ignore this comment, let's remove the codeblock instead of commenting out

2016-11-14 22:44 UTC, hakankaradis commented
@gokmen http://recordit.co/xbkeG2RR5N

2016-11-15 09:22 UTC, gokmen commented
@hakankaradis can u assign back to me once it's ready, thanks!

2016-11-17 08:29 UTC, gokmen requested changes
LGTM but there are some changes required for code structure let's have another session to finalise those issues. Then we can merge this in, thanks!

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/components/sidebar/index.coffee
> +        computeController.sharingStackTemplate draft.get('_id'), 'group'
can we rename this function to `shareStackTemplate`

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/components/sidebar/index.coffee
> +      menuItems['Edit'] = { callback }
won't this change prevent admins to edit team stacks from sidebar?

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/components/sidebar/index.coffee
> +      menuItems['View Stack'] = { callback }
hmm this one covers that case, ok.

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/components/sidebar/index.coffee
> +        else  menuItems['Make Private'] = { callback }
👍

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +      template.setAccess type
let's remove this helper from here and use where needed as is and rename it as `setTemplateAccessLevel`

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +  setStackTemplateAccessLevel: (params) ->
maybe we can move this out of computecontroller since it's not doing anything related with computecontroller but stores it seems.

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +
👍

2016-11-17 08:29 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +  removeClonedFromAttr: (stackTemplate, callback = kd.noop) ->
I think we can move this functionality to `JStackTemplate` itself.

2016-11-18 19:19 UTC, hakankaradis commented on client/app/lib/providers/computecontroller.coffee
> +      template.setAccess type
What helper?

2016-11-18 20:34 UTC, hakankaradis commented on client/app/lib/providers/computecontroller.coffee
> +  removeClonedFromAttr: (stackTemplate, callback = kd.noop) ->
This function clean the JComputeStack and JStackTemplate instance's config information.
And update instance and stores.
Do you want me to put this functionality to `JStackTemplate` just for clean `clonedFrom` and `needUpdate` attributes?

2016-11-18 20:34 UTC, hakankaradis commented on client/app/lib/providers/computecontroller.coffee
> +  setStackTemplateAccessLevel: (params) ->
Actually it does, It is using `checkRevisionFromOrifinalStackTemplate` and update the JComputeStack instance.

2016-11-18 20:34 UTC, hakankaradis commented on client/app/lib/providers/computecontroller.coffee
> +      template.setAccess type
do you want me to update this function name?
https://github.com/koding/koding/blob/master/workers/social/lib/social/models/computeproviders/stacktemplate.coffee#L56

2016-11-21 12:08 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +  setStackTemplateAccessLevel: (params) ->
yes, it does. but it's updating stacks individually which needs to be handled by stack itself.

2016-11-21 12:09 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +  removeClonedFromAttr: (stackTemplate, callback = kd.noop) ->
yes, we may need to move some functionality into backend like these. we'll need such functionality over api support and in that case we'll end-up with duplicate codes.

2016-11-21 12:10 UTC, gokmen commented on client/app/lib/providers/computecontroller.coffee
> +      template.setAccess type
yes, `sharingStackTemplate` tells something ongoing but we need to put the action into method name not the state.

2016-11-22 00:15 UTC, gokmen approved these changes

2016-11-22 00:15 UTC, merged