API Support
koding/koding pull request #9548
Opened 2016-11-11 20:47 UTC by gokmen

## Description
This PR will provide REST api for Koding Node backend with proper cookie or token or for public requests. **This is currently experimental and wip.**

## Screenshots (if appropriate):
![image](https://cloud.githubusercontent.com/assets/42368/20229599/076e3f64-a860-11e6-8fe4-aa79e98fdaf9.png)

## TODO
 - [x] Add support for descriptions in schema on `Bongo::Model`
 - [x] Generate initial model definitions for Swagger api generator from Bongo models
 - [  ] Generate api endpoints for static methods of models
 - [  ] Generate api endpoints for instance methods of models
 - [x] Remote API handler for initial requests
 - [ ] Enable throttling on remote endpoint
 - [ ] Tests needs to be written for the api
 - [ ] Setup Swagger-UI in place to provide auto generated api docs
 - [ ] Auto generate swagger.yaml on model change, serve it under website

2016-11-11 20:51 UTC, usirin commented
![](https://media.giphy.com/media/amkxRknWsbWtG/giphy.gif)

2016-11-17 09:49 UTC, cihangir approved these changes

2016-11-17 09:49 UTC, cihangir commented on node_modules_koding/bongo/lib/bongo.coffee
> +    console.warn '[Bongo:UserError]', message, args
👍

2016-11-17 09:49 UTC, cihangir commented on node_modules_koding/bongo/lib/expressify.coffee
> +              return res.status(500).send 'An error occcurred'
what about a more informative message or a log statement?

2016-11-17 09:49 UTC, cihangir commented on workers/social/lib/social/models/account.coffee
> -        cursor:
👍

2016-11-17 09:50 UTC, cihangir commented
could you please make sure swagger.json is always up-to-date with the current codebase in CI env?

2016-11-17 10:17 UTC, szkl commented on workers/social/lib/social/models/session.coffee
> +    @one { clientId: client.sessionToken }, callback
Would it be good to match username and group too?

2016-11-17 10:18 UTC, gokmen commented on workers/social/lib/social/models/session.coffee
> +    @one { clientId: client.sessionToken }, callback
I don't have those information, just getting token from header. But using the `username` and `group` in returned `JSession` object.

2016-11-17 10:19 UTC, szkl commented on workers/social/lib/social/models/session.coffee
> +    @one { clientId: client.sessionToken }, callback
Okay. I thought `client` would have them.

2016-11-17 10:20 UTC, gokmen commented
> could you please make sure swagger.json is always up-to-date with the current codebase in CI env?

@cihangir sure thing! At first I was planning to not to keep swagger.json in repo but then I thought it might be a good thing to see what is changed on api. I'll add a wercker step to verify swagger.json with the code.

2016-11-17 10:22 UTC, gokmen commented on workers/social/lib/social/models/session.coffee
> +    @one { clientId: client.sessionToken }, callback
ah sorry, I thought you were asking for some place else, you're right I can add that check here. 👊

2016-11-17 10:35 UTC, cihangir commented
I also liked the idea of keeping swagger def in the repo 👍  💯

2016-11-22 16:53 UTC, gokmen commented
I'm done with this shall we merge? cc/ @cihangir @usirin @szkl @rjeczalik

2016-11-22 18:45 UTC, rjeczalik approved these changes

2016-11-23 10:14 UTC, cihangir commented on workers/social/lib/social/remoteapi.coffee
> +KONFIG    = require 'koding-config-manager'
could you write test for this file?

2016-11-23 10:18 UTC, cihangir requested changes

2016-11-23 10:18 UTC, cihangir commented on workers/social/lib/social/models/session.coffee
> +    @one { username, clientId }, callback
clientId is enough, we dont need username + we dont have index on these two

2016-11-23 10:18 UTC, cihangir commented on workers/social/lib/social/models/computeproviders/providerinterface.coffee
> +# @example How to subclass a provider
👍

2016-11-23 10:18 UTC, cihangir commented on wercker.yml
> +        code: scripts/wercker/run-command ./run exec scripts/api-generator.coffee --check
👍

2016-11-23 11:38 UTC, cihangir approved these changes
💯

2016-11-23 11:38 UTC, merged