Implemented Notification Component
koding/koding pull request #9592
Opened 2016-11-16 16:23 UTC by drewsetski

## Description
Created notification in component-lab folder

## Fast guide 
```
@_notification.addNotification
     type : ['success', 'update', 'warning', 'caution']
     duration : integer (ms)
     dismissible : boolean
     content : string
     primaryButtonTitle : string
     onPrimaryButtonClick : function
     secondaryButtonTitle : string
     onSecondaryButtonClick : function
     noAnimation : boolean
```

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

> Video: [https://www.dropbox.com/s/3rgwc65kkngaivq/KdNotifications.mov?dl=0](url)
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-11-16 16:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/koding/koding?pullRequest=9592) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/koding/koding?pullRequest=9592) before we can accept your contribution.<br/>

2016-11-16 19:38 UTC, hakankaradis reviewed
Thanks for your first pull request.
It looks good but there are some minor problems.

In component-lab folder, we have box and buttons components, I think it will be better to implement style with those components /cc: @usirin

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/NotificationView.coffee
> +            <button type="button"
Indentation!
For those kind of dom elements, you can separate them to out of class
[See this example](https://github.com/koding/koding/blob/master/client/home/lib/myteam/components/hometeamteammates/view.coffee#L63)

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/NotificationView.coffee
> +    getInitialState: ->
constructor

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/NotificationView.coffee
> +    getDefaultProps: ->
```coffeescript
@defaultProps =
  onRemove: kd.noop
```

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/NotificationView.coffee
> +module.exports = NotificationView = React.createClass
Same here, use React.Component

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.stylus
> +  bottom                        0
It should come from top, not bottom
`top 0`

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +        ref={"notification-#{notification.uid}"}
https://facebook.github.io/react/docs/refs-and-the-dom.html
Check the usage of refs in React. We better use them in this way.

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +    return
I don't think you need `return` statement here

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +      @setState notifications : notifications
`@setState { notifications : notifications }`
[our coffee style guide](https://github.com/koding/styleguide-coffeescript) here

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +    self = this
no need this

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +    _notification = Object.assign({}, Constants.notification, notification)
use `lodash` here, instead of `Object`

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +  getInitialState: ->
```coffeescript
constructor: (props) ->
  super props
  @state = 
    notifications: []
    noAnimation: no
```

2016-11-16 19:38 UTC, hakankaradis commented on client/component-lab/Notification/Notification.coffee
> +module.exports = Notification = React.createClass
Convert it with React.Component
`React.Component`

2016-11-17 21:47 UTC, drewsetski commented
Hello! I've done fixes by your comments and added animation on appearing/disappearing of notification. 
> Here is link of video-demonstration: https://www.dropbox.com/s/adogzsy84eg4mjc/notifications2.mov?dl=0

2016-11-18 19:28 UTC, hakankaradis commented
@drewsetski Thanks for updates,
About styling, buttons in the view shouldn't have background color when you hover it.
The padding from top for icon should be 13px.
And can you also put the example of the basic NotificationView as well?

2016-11-18 21:35 UTC, usirin requested changes
It looks really good overall. Lots of style guide related changes are required, but it shouldn't be hard to apply all those changes.

When you finish the requested changes i will go over the whole Pull Request again.

2016-11-18 21:35 UTC, usirin commented on client/component-lab/Notification/Notification.stylus
> +      height                    48px
/cc @sinan

2016-11-18 21:35 UTC, usirin commented on client/component-lab/Notification/NotificationView.coffee
> +ReactDOM = require('react-dom')
remove

2016-11-18 21:35 UTC, usirin commented on client/package.json
> +    "react-flip-move": "^2.6.10",
We are using only the locked versions of npm packages, remove `^` here.

2016-11-22 00:36 UTC, drewsetski commented
> Video: 
https://www.dropbox.com/s/j8n9hqmggczx49i/notifications3.mov?dl=0

2016-11-22 15:55 UTC, usirin approved these changes

2016-11-22 15:55 UTC, usirin commented
I like what i see here, if @sinan is ok with the css changes we can merge this in.

Really good job @drewsetski 💯

2016-11-22 21:30 UTC, sinan commented on client/component-lab/Notification/Notification.stylus
> +@import '~lab/Colors/Colors.stylus'
please rename the style files with a `styl` extension

2016-11-22 22:12 UTC, sinan requested changes
thx @drewsetski I have some change requests, and had a talk with @usirin & @hakankaradis, they will also have further requests here.

2016-11-22 22:14 UTC, sinan commented on client/component-lab/Notification/NotificationView.coffee
> +      if @autoDismissible(@props.notification)
i did not comment on every occurrence, please take another look at your changes and apply these comments to wherever it applies.

2016-11-22 22:34 UTC, drewsetski commented on client/component-lab/Notification/NotificationView.coffee
> +      if @autoDismissible(@props.notification)
Thanks for the comments. I will fix it and push ASAP

2016-11-22 23:07 UTC, usirin commented on client/component-lab/Notification/Notification.stylus
> +@import '~lab/Colors/Colors.stylus'
He needs to keep it this way, because `stylus` extension is required for local scoped css.

2016-11-22 23:18 UTC, hakankaradis requested changes
- Define a `NotificationViewController` under `app/lib` directory
- Init this and include inside `MainController` ([example](https://github.com/koding/koding/blob/master/client/app/lib/maincontroller.coffee#L103))
- This will be available for you as `kd.singletons.notificationViewController`
- Once you want to add a notification you will use `kd.singletons.notificationViewController.addNotification ...

- To do that, you need to move all the business logic from `Notification.coffee` into `NotificationViewController`
- You will create a new container class but not as a `React.Component` but as a `ReactView` (a kd.View not a React.Component)
- You will create this container once in the lifetime of the application, and you will add this into the dombody.
- One extra thing we need to do is creating a `ReactView` instance who is responsible for rendering a new Notification component, and creating this `ReactView` instance will be job of our new `NotificationViewController`.

```coffee
# notificationviewcontroller.coffee
kd = require 'kd'
# this is the new ReactView instance we created.
NotificationContainerView = require '...' 

class NotificationViewController extends kd.Controller

  constructor: (options = {}, data) ->
    super options, data
    ...
    @container = new NotificationContainerView
    # this makes sure that our new class is added body seperately.
    @container.appendToDomBody()
```

- Once `notificationViewController.addNotification` is called, this class will call `@updateOptions { ... }` on the new `ReactView` instance, and the ReactView instance will render a new `NotificationView` component with given options. 

```coffee
# notificationviewcontroller.coffee
class NotificationViewController extends kd.Controller
  # ...
  addNotification: (notificationOptions) -> 
    notifications.push notificationOptions # this is just a pseudo-code
    @container.updateOptions { notifications }
  # ...
```
- You can check out [from here](https://github.com/koding/koding/blob/bc72c1f487887ae9f8cc7ea59a0e1770d3f6b5e4/client/ide/lib/test/browser/index.coffee#L69-L93) as a reference implementation for a class that extends `ReactView`

```coffee
# notificationcontainer.coffee
ReactView = require 'app/react/reactview'
class NotificationContainer extends ReactView
  renderReact: ->
    return <span />  unless @options.notifications.length
    
    @options.notifications.map (notification) ->
      <NotificationView ... />
```
/cc: @usirin

2016-11-23 23:32 UTC, hakankaradis requested changes

2016-11-23 23:32 UTC, hakankaradis commented on client/component-lab/Notification/helpers.coffee
> +propsValidation = (notification, types) ->
change to `validateProps`

2016-11-23 23:37 UTC, sinan commented on client/component-lab/Notification/helpers.coffee
> +  if _.keys(types).indexOf(notification.type) is -1
`lodash` again, this is the second time I notice this. This should break your own environment, do you push untested code?

2016-12-02 17:36 UTC, closed without merging