Remove cors middleware
koding/koding pull request #9700
Opened 2016-11-23 13:18 UTC by szkl

Signed-off-by: Sonmez Kartal <sonmez@koding.com>

2016-11-23 13:20 UTC, szkl commented
CORS headers are set by nginx configuration [here](https://github.com/koding/koding/blob/master/deployment/nginx.coffee#L132-L137).

2016-11-23 13:22 UTC, gokmen commented
do we need to remove this one as well? https://github.com/koding/koding/blob/master/workers/social/lib/social/main.coffee#L153

2016-11-23 13:26 UTC, szkl commented
@gokmen it should stay. CORS is not enabled for social worker in nginx location directive.

2016-11-23 13:26 UTC, gokmen approved these changes

2016-11-23 16:15 UTC, sinan commented
With this will cors work in dev instances (non-prod)?

2016-11-23 17:19 UTC, szkl commented
I think workers don't have CORS enabled by default. We can make script generating nginx configuration to enable CORS for any domain in non-prod configuration.

2016-11-23 19:05 UTC, sinan approved these changes
alright, the `cors()` lines you deleted made it work in dev machines. We can take this in but we need to create another ticket to make those endpoints work in dev instances.

2016-11-24 09:29 UTC, cihangir approved these changes

2016-11-24 09:30 UTC, cihangir requested changes
please rebase

2016-11-24 10:46 UTC, szkl commented
I will add a wildcard CORS header in this pull request after rebasing.

2016-11-28 10:19 UTC, gokmen commented
ping @szkl

2016-11-28 18:33 UTC, szkl commented
Updated.

2016-11-28 23:24 UTC, szkl commented
I've found out nginx in test AMI is a bit old.

2016-11-29 15:10 UTC, cihangir approved these changes

2016-11-29 15:11 UTC, cihangir commented
Could you rebase again just to trigger the test?

2016-11-29 17:26 UTC, gokmen commented
@szkl tests seems failing, can you check?

2016-11-29 17:28 UTC, szkl commented
I'm on it.

2016-12-01 20:16 UTC, gokmen commented on deployment/nginx.coffee
> +        cors = "add_header 'Access-Control-Allow-Origin' '*' always;"
this might misdirect developers, some feature will work on their locals but it will be broken when they've pushed. just say'n.

2016-12-01 20:16 UTC, gokmen approved these changes
LGTM except https://github.com/koding/koding/pull/9700/files#r90528424

2016-12-02 09:11 UTC, merged