Implemented NotificationView
koding/koding pull request #9757
Opened 2016-11-25 10:39 UTC by drewsetski

## Description
I've created new pull request because I had to merge with last changes on main repository and there were conflicts

## Fast guide 
```
kd.singletons.notificationViewController.addNotification
     type : ['success', 'update', 'warning', 'caution']
     duration : integer (ms)
     dismissible : boolean
     content : string
     primaryButtonTitle : string
     onPrimaryButtonClick : function
     secondaryButtonTitle : string
     onSecondaryButtonClick : function
```

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-11-25 21:04 UTC, drewsetski commented
> Video: https://www.dropbox.com/s/y8q3an8xgoquc0p/notificationsViewController.mov?dl=0

2016-12-03 01:58 UTC, usirin requested changes

2016-12-06 21:45 UTC, drewsetski commented
I've pushed little fix to conditions, but it hadn't appear on github...

2016-12-07 19:39 UTC, hakankaradis requested changes
Can you please check once again the styles.
![](https://monosnap.com/file/on7t5pZGpOC2X0AmEKkodOqelPDrBa.png)
It doesn't work properly.
Thanks

2016-12-07 19:39 UTC, hakankaradis commented on client/component-lab/Notification/NotificationView.coffee
> +      @isMounted = no
`@isMounted` is a special function in Reactjs. It throws some warning, [check from here](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html)

2017-01-03 19:54 UTC, gokmen commented
what is the latest status about this? cc/ @usirin @hakankaradis

2017-01-03 19:58 UTC, hakankaradis approved these changes

2017-01-03 20:02 UTC, hakankaradis commented
@gokmen I believe it is ready to go.
After @usirin  approves the changes, I will pull the branch and open new pull request to run our tests
That means we will not merge this pr.

2017-01-05 08:13 UTC, hakankaradis commented
@gokmen, @usirin pr is reopened  #10218, fyi

2017-01-06 12:43 UTC, closed without merging