Klient block
koding/koding pull request #9882
Opened 2016-12-05 13:57 UTC by ppknap

Remote auto-updated clients will refuse callers' request when klient's team is blocked due to unpaid subscription.

Depends on: #9870 

| Method   |      Callers      |  Blocked | Command |
|----------|:-------------:|:------:|:-------:|
| `klient.usage` |  kloud | :x: | - |
| `os.home` |    klient   | :white_check_mark: | - | 
| `os.currentUsername` | klient | :white_check_mark: | ssh |
| `klient.info` | klient | :white_check_mark: | list |
| `klient.disable` | browser | :x: | - |
| `klient.share` | kloud/browser/socialapi | :x: | - |
| `klient.unshare` | kloud/browser/socialapi | :x: | - |
| `klient.shared` | browser/socialapi | :x: | - |
| `sshkeys.list` | - | :white_check_mark: | - |
| `sshkeys.add` | klient | :white_check_mark: | ssh |
| `sshkeys.delete` | - | :white_check_mark: | - |
| `storage.set` | browser | :x: | - |
| `storage.get` | browser | :x: | - |
| `storage.delete` | browser | :x: | - |
| `log.tail` | browser | :x: | - |
| `fs.readDirectory` | browser/klient | :white_check_mark: | mount |
| `fs.glob` | browser/klient | :white_check_mark: | mount |
| `fs.readFile` | browser/klient | :white_check_mark: | mount |
| `fs.writeFile` | browser/klient | :white_check_mark: | mount |
| `fs.uniquePath` | browser/klient | :white_check_mark: | mount |
| `fs.getInfo` | browser/klient | :white_check_mark: | mount |
| `fs.setPermissions` | browser/klient | :white_check_mark: | mount |
| `fs.remove` | broser/klient | :white_check_mark: | mount |
| `fs.rename` | browser/klient | :white_check_mark: | mount |
| `fs.createDirectory` | browser/klient | :white_check_mark: | mount |
| `fs.move` | browser/klient | :white_check_mark: | mount |
| `fs.copy` | klient | :white_check_mark: | mount |
| `fs.getDiskInfo` | klient | :white_check_mark: | mount |
| `fs.getPathSize` | klient | :white_check_mark: | mount |
| `vagrant.create` | kloud | :x: | - |
| `vagrant.provider` | kloud | :x: | - |
| `vagrant.list` | kloud | :x: | - |
| `vagrant.up` | kloud | :x: | - |
| `vagrant.halt` | kloud | :x: | - |
| `vagrant.destroy` | kloud | :x: | - |
| `vagrant.status` | kloud | :x: | - |
| `vagrant.version` | kloud | :x: | - |
| `vagrant.listForwardedPorts` | klient | :x: | - |
| `tunnel.info` | kloud | :x: | - |
| `log.upload` | - | :x: | - |
| `webterm.getSessions` | browser | :white_check_mark: | - |
| `webterm.connect`  | browser | :white_check_mark: | - |
| `webterm.killSession` | browser | :white_check_mark: | - |
| `webterm.killSessions` | browser | :white_check_mark: | - |
| `webterm.rename` | browser | :white_check_mark: | - |
| `client.Publish` | KD | :x: | - |
| `client.Subscribe` | browser | :x: | - |
| `client.Unsubscribe` | browser | :x: | - |
## Motivation and Context
Payment handling

## How Has This Been Tested?
Manually

2016-12-07 11:01 UTC, rjeczalik commented on go/src/koding/klient/app/klient.go
> +			k.log.Error("Cannot find Klient's team: %s", err)
Won't work for KD for a reason stated in previous PR.

2016-12-14 18:22 UTC, rjeczalik commented on go/src/koding/klient/app/klient.go
> +	k.handleWithSub("os.home", kos.Home)
How about making this more configurable?

Create a configuration map [like this one](https://github.com/koding/koding/pull/9882/commits/1389cf689dcee7f2cd0d1fed465fbe33a7e82bb1#diff-514e03b9d69e198098d3560e3bda3763R213), and register a PreHandlerFunc that if sub-check is requested, will validate it and return error if sub is not valid. Basically would work the same as auth check etc.

2016-12-14 18:31 UTC, ppknap commented on go/src/koding/klient/app/klient.go
> +	k.handleWithSub("os.home", kos.Home)
your link is broken

2016-12-14 20:28 UTC, rjeczalik commented on go/src/koding/klient/app/klient.go
> +	k.handleWithSub("os.home", kos.Home)
> If yes, why didn't you use proposed solution in your presence logic?

The idea just popped to my head why I was reading this klient.go file, remote.go was pretty raw. If you don't see a benefit then there's no need for changes. :-)

2016-12-15 04:41 UTC, ppknap commented on go/src/koding/klient/app/klient.go
> +	k.handleWithSub("os.home", kos.Home)
Honestly speaking, the current form was based on your solution for `remote` methods and I'm not against other ideas. Personally, I would have written something like:

```go
package subscription

type Check struct {
    Team func() (team.Team error) // team getter.
}

func (c *Check) Check() {
  // business logic here
}

// ...

func KiteCheck(c *Check, h kite.Handler) kite.Handler {
  return kite.HandlerFunc(func(req *Request) (result interface{}, err error) {
    if err := c.Check(); err != nil { // validation logic
      return nil, err
    }
    return h(req)
  })
}

```
and 
```go
k.kite.Handle("os.currentUsername", subscription.KiteCheck(c, kite.HandlerFunc(kos.CurrentUsername)))
```
With this, I could test the logic separately from klient/kite. But, I know that I sometimes overdo with my architecture ideas so I'm trying to not push them on anyone. :)

2016-12-15 09:24 UTC, rjeczalik approved these changes

2016-12-15 10:09 UTC, cihangir requested changes

2016-12-15 10:09 UTC, cihangir commented on go/src/koding/kites/kloud/stack/whoami.go
> +func (t *Team) IsSubActive() bool {
lets not duplicate the logic, and have the critical logic in one place, please refactor this and the one we have in group.go to use the exact same code.

2016-12-15 19:11 UTC, ppknap commented
@cihangir done

2016-12-16 08:01 UTC, cihangir approved these changes

2016-12-16 08:04 UTC, cihangir commented
go build is failing, could you do repo-wide `s/PaymentStatusActive/SubStatusActive` ? You can merge when tests passes

2016-12-22 10:44 UTC, rjeczalik approved these changes

2016-12-22 10:44 UTC, merged