Fix/Reword email instructions for Rainforest test #49632
koding/koding pull request #9902
Opened 2016-12-06 06:02 UTC by bitspill

The usage of `rainforest+random.email` appears to have been causing troubles at Step.3 where it would claim an account already existed with that email, also adjusted wording later on when viewing the random.inbox

This pull request is an attempt at partially fulfilling #9891 and I would like to verify I'm doing what's expected before proceeding to any further changes. I can also be found on Slack as `@bitspill`

2016-12-06 06:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/koding/koding?pullRequest=9902) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/koding/koding?pullRequest=9902) before we can accept your contribution.<br/>

2016-12-07 12:54 UTC, diclee requested changes

2016-12-07 12:54 UTC, diclee commented on tests/spec/rainforest/joinByInvitation_logout_tryToLoginWith_NotAllowedEmail_InvalidPassword.rfml
> +Enter "{{ random.email }}" in the 'Email Address' and "{{ random.last_name }}{{ random.number }}" in 'Team Name' fields and click on 'NEXT' button
`{{ random.email }}` doesn't solve the problems that `rainforest+{{ random.email }}` may cause. They have the same randomness. Also changing this value as `{{ random.email }}` breaks the next steps of the test where ``{{ random.email }}` is invited as a member (https://github.com/koding/koding/pull/9902/files?diff=split#diff-8f80098be99204fe0da8b9e9f3308253R25)

2016-12-07 14:37 UTC, bitspill commented on tests/spec/rainforest/joinByInvitation_logout_tryToLoginWith_NotAllowedEmail_InvalidPassword.rfml
> +Enter "{{ random.email }}" in the 'Email Address' and "{{ random.last_name }}{{ random.number }}" in 'Team Name' fields and click on 'NEXT' button
It's not that both emails are randomly being generated to be the same but that koding appears to only check prior to the `+` for uniqueness

https://github.com/koding/koding/blob/ba0fa3efcbcb26eb1ce7aa5612dc405db37e32a8/workers/social/lib/social/models/user/emailsanitize.coffee#L18
https://github.com/koding/koding/blob/ba0fa3efcbcb26eb1ce7aa5612dc405db37e32a8/workers/social/lib/social/models/user/emailsanitize.test.coffee#L38

Admittedly I'm not overly familiar with the codebase so those functions may not apply here but the behavior seems to fit.

2016-12-08 09:43 UTC, diclee approved these changes

2016-12-10 02:50 UTC, szkl requested changes

2016-12-10 02:50 UTC, szkl commented on tests/spec/rainforest/joinByInvitation_logout_tryToLoginWith_NotAllowedEmail_InvalidPassword.rfml
> +Do you see a newly recieved email with subject 'You are invited to join a team on Koding'? (may take a minute or so to appear)
Typo.

2016-12-10 03:25 UTC, bitspill commented
@szkl Fixed typo and condensed to a single commit

2016-12-10 23:03 UTC, szkl approved these changes

2016-12-10 23:04 UTC, szkl commented
Fix will be verified with next test runs.

2016-12-10 23:04 UTC, merged

2016-12-13 04:21 UTC, szkl commented
Fix for modified 2 steps are verified.