Business addons
koding/koding pull request #9960
Opened 2016-12-09 03:03 UTC by drewsetski

## Description

In order to link the activation of plans and add-on and unlock it's features `koding button`, `chatlio`, `intercom`, I have to use Redux/Flux later for storing general states.
Deactivations of plan, add-on are not implemented. Also tooltip isn't done, because `Tabs` in `HomeAppView` doesn't except any other prop.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-12-09 21:30 UTC, sinan commented
@drewsetski can you pls share a screencast or some screenshots?

2016-12-12 19:24 UTC, drewsetski commented
Here is video:
https://www.dropbox.com/s/nwqdjxpxwgnxgp0/AddOns.mov?dl=0
Interactivity will be finished with Redux states

2016-12-21 13:13 UTC, hakankaradis requested changes
There are many indentation problems in stylus files and wrong usage of double quote

2016-12-21 13:13 UTC, hakankaradis commented on client/component-lab/Banner/Banner.story.coffee
> +      type="primary"
https://github.com/koding/styleguide-coffeescript#use-single-quotes-if-there-is-no-string-interpolation

2016-12-21 13:13 UTC, hakankaradis commented on client/component-lab/Banner/StoryStyles.stylus
> +  padding					  		48px
indentation

2016-12-21 13:13 UTC, hakankaradis commented on client/component-lab/Modal/Modal.coffee
>          {secondaryButtonTitle}
Will not be `size='undefined'`  if size ?

2016-12-21 13:13 UTC, hakankaradis commented on client/home/lib/billing/components/subscriptionsection.coffee
> +      <AddonsBanner />
I believe showing AddonsBanner should be tied to any condition to show it to user.
We might provide you more info about when it should be showed or not

2016-12-21 13:13 UTC, hakankaradis commented on client/home/lib/addons/index.coffee
> +    return null
Is there any info that you are waiting from us to implement the Redux stores?

2016-12-21 13:13 UTC, hakankaradis commented on client/home/lib/addons/homebusinessaddondeactivation.coffee
> +  renderReact: -> <PlanDeactivation.Container target="BUSINESS ADD-ON" onDeactivation={@bound 'deactivateBusinessAddOn'}/>
should be in next line.

2016-12-21 13:13 UTC, hakankaradis commented on client/home/lib/addons/homesupportplandeactivation.coffee
> +  renderReact: -> <PlanDeactivation.Container target="#{@getActivePlan()} SUPPORT PLAN" onDeactivation={@bound 'deactivateSupportPlan'}/>
same here

2016-12-21 13:14 UTC, hakankaradis commented on client/component-lab/SupportPlan/SupportPlan.story.coffee
> +          name={plan.name}
indentation

2016-12-21 13:16 UTC, drewsetski commented on client/component-lab/Banner/StoryStyles.stylus
> +  padding					  		48px
perhaps switch between tabs and spaces was jumping back and forth after each opening of file

2017-01-11 14:46 UTC, hakankaradis requested changes
Thanks for changes @drewsetski 

There is a problem with usage of Redux.
Please check [this link](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.8j9784w0z) to understand the difference between `Presentational and Container Components`

Here is what you need to do.
You will need 2 different containers to manage component's state and passing actions via props.

You need to add a containers folder under `home/lib/addons/` directory
one will be businessaddons.coffee

```coffee
React = require 'react'
{ connect } = require 'react-redux'
addon = require 'app/redux/modules/payment/addon'
BusinessAddons = require '../components/businessaddons'

mapStateToProps = (state) ->
  return {
    addonStatus: addon.isActivated state
    kodingButtonStatus: addon.isKodingButtonActivated state
    intercomStatus: addon.isIntercomActivated state
  }

mapDispatchToProps = (dispatch) ->
  return {
    onActivateBusinessAddOn: -> dispatch(addon.create())
    onDeactivateBusinessAddOn: -> dispatch(addon.remove())
    toggleModal: -> dispatch(addon.toggleModal())
    onActiveKodingButton: -> dispatch(addon.activeKodingButton())
    onActiveIntercom: -> dispatch(addon.activeIntercom())
    onActiveChatlio: -> dispatch(addon.activeChatlio())
  }

module.exports = connect(
  mapStateToProps
  mapDispatchToProps
)(BusinessAddons)
```
And also you will need to add wrapper component to manage e,g, business addons components

You need to pass components states and actions to businessaddons component.

So you will also need to add another folder which is called businesscomponent under `home/lib/addons/components/businessaddons`

`container.coffee` will be like 
```coffee
React = require 'app/react'
View = require './view'
kd = require 'kd'
{ Provider } = require 'react-redux'

module.exports = class BusinessAddOnContainer extends React.Component

  render: ->

    <Provider store={kd.singletons.store}>
      <View />
    </Provider>
```

view.coffee will be like 
```coffee
React = require 'app/react'

Box = require 'lab/Box'
Button = require 'lab/Button'
SupportPlanActivationModal = require 'lab/SupportPlanActivationModal'
{
  Container
  Header
  Message
  Divider
  List
  Footer
  Actions
  PriceSegment
} = Banner = require 'lab/Banner'

class BusinessAddOns extends React.Component

  render: ->

    <div>
      {
        <div>
          <Banner
            type='primary'
            image='banner_business_add_on'
            className='Banner'>
            <Container>
              <Header
                heading='Empower Your Koding with'
                target='Business Add-On'/>
              <Message>
                Fusce dapibus, tellus ac cursus commodo, tortor mauriscondimentum nibh, ut fermentum massa justo sit amet risus.
              </Message>
              <Divider />
              <List
                title='Features'
                items={[
                  'Try on Koding functionality'
                  'Direct communication with leads through <br/> Intercom and Chatlio Integration'
                  'Analytics (Coming soon)'
                ]} />
              <Footer>
                <a href='/Home/add-ons/business-add-on#koding-button'>See what you will get with Business Add-On below</a>
              </Footer>
            </Container>
            <Actions className='Actions'>
              <PriceSegment
                price={@price}
                onClick={@props.toggleActivationModal()}
                link='https://www.koding.com/pricing'/>
            </Actions>
          </Banner>
          <SupportPlanActivationModal
            isOpen={@props.modalOpen}
            title='Business Add On'
            image='business_add_on_activation'
            label='Business Add On'
            price={@price}
            shouldCloseOnOverlayClick={yes}
            onCancel={@props.toggleActivationModal()}
            onActivateSupportPlanClick={@props.activateBusinessAddOn()} />
        </div>  unless @props.addonStatus
      }
    </div>

module.exports = BusinessAddOns
```

You need to do this for support plan tab as well.
I mean you will add another container `home/lib/addons/containers/supportplan.coffee` and also a wrapper component to manage the support plan component's state and its actions

/cc: @usirin can you also please review the code?

2017-01-11 14:46 UTC, hakankaradis commented on client/home/lib/addons/components/addondeactivation/view.coffee
> +  module.exports = connect(
view.coffee files should only be responsible for rendering view with given props.
This usage is against the terminology.

2017-01-11 14:46 UTC, hakankaradis commented on client/home/lib/addons/components/supportplans/view.coffee
> +  module.exports = connect(
same here, these props should be passed from `container`

2017-01-11 14:46 UTC, hakankaradis commented on client/home/lib/addons/components/supportplandeactivation/view.coffee
> +  module.exports = connect(
same here!

2017-01-11 15:02 UTC, hakankaradis commented
@sinan Can you please provide us correct copies for those pages.
![](https://monosnap.com/file/W0n1sLcWzbvngAQxcr6Nc5MW2OyYi7.png)
![](https://monosnap.com/file/dYUmebBKsGHVE27rUpwpytLFcGjOhw.png)
![](https://monosnap.com/file/3xJhI4CZb5DIEXnFQvTkVQYPTvOcJE.png)

2017-01-23 21:13 UTC, hakankaradis requested changes

2017-01-23 21:13 UTC, hakankaradis commented on client/component-lab/Banner/Banner.coffee
> +formatMoney = require 'app/util/formatMoney'
You are missing that util `formatMoney`

2017-01-23 21:13 UTC, hakankaradis approved these changes

2017-01-23 21:14 UTC, hakankaradis requested changes
@drewsetski 
Everything looks good to me.
![](https://monosnap.com/file/IeodIHVPqjMf25xTxHAOwKtjLxYYX2.png)

But we are missing this feature in this pr.
The selected add-ons and support plans should be visible on the `Team Billing` section.
Once we have this then we can merge this pr

2017-01-25 22:56 UTC, hakankaradis commented
Closing this pr, it is reopened here #10425

2017-01-25 22:56 UTC, closed without merging